table dim_zone

	column zone_id
		dataType: int64
		summarizeBy: none
		sourceColumn: zone_id

	column zone_name
		dataType: string
		summarizeBy: none
		sourceColumn: zone_name

	column is_synthetic
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_synthetic

	partition dim_zone = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/dim_zone.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"zone_id", Int64.Type}, {"zone_name", type text}, {"is_synthetic", type logical}}, "en-CA")
				in
				    Typed
