table experiment_results

	column difference
		dataType: double
		summarizeBy: none
		sourceColumn: difference

	column ci_low
		dataType: double
		summarizeBy: none
		sourceColumn: ci_low

	column ci_high
		dataType: double
		summarizeBy: none
		sourceColumn: ci_high

	column p_value
		dataType: double
		summarizeBy: none
		sourceColumn: p_value

	column p_adjusted
		dataType: double
		summarizeBy: none
		sourceColumn: p_adjusted

	column arm
		dataType: string
		summarizeBy: none
		sourceColumn: arm

	column n
		dataType: int64
		summarizeBy: none
		sourceColumn: n

	column conversion
		dataType: double
		summarizeBy: none
		sourceColumn: conversion

	column relative_lift
		dataType: double
		summarizeBy: none
		sourceColumn: relative_lift

	partition experiment_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/experiment_results.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"difference", type number}, {"ci_low", type number}, {"ci_high", type number}, {"p_value", type number}, {"p_adjusted", type number}, {"arm", type text}, {"n", Int64.Type}, {"conversion", type number}, {"relative_lift", type number}}, "en-CA")
				in
				    Typed
