table experiment_subgroups

	column dimension
		dataType: string
		summarizeBy: none
		sourceColumn: dimension

	column group
		dataType: string
		summarizeBy: none
		sourceColumn: group

	column arm
		dataType: string
		summarizeBy: none
		sourceColumn: arm

	column n_treatment
		dataType: int64
		summarizeBy: none
		sourceColumn: n_treatment

	column n_control
		dataType: int64
		summarizeBy: none
		sourceColumn: n_control

	column difference
		dataType: double
		summarizeBy: none
		sourceColumn: difference

	column ci_low
		dataType: double
		summarizeBy: none
		sourceColumn: ci_low

	column ci_high
		dataType: double
		summarizeBy: none
		sourceColumn: ci_high

	column p_value
		dataType: double
		summarizeBy: none
		sourceColumn: p_value

	column p_adjusted
		dataType: double
		summarizeBy: none
		sourceColumn: p_adjusted

	partition experiment_subgroups = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/experiment_subgroups.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"dimension", type text}, {"group", type text}, {"arm", type text}, {"n_treatment", Int64.Type}, {"n_control", Int64.Type}, {"difference", type number}, {"ci_low", type number}, {"ci_high", type number}, {"p_value", type number}, {"p_adjusted", type number}}, "en-CA")
				in
				    Typed
