table feature_drift

	column feature
		dataType: string
		summarizeBy: none
		sourceColumn: feature

	column psi
		dataType: double
		summarizeBy: none
		sourceColumn: psi

	column ks_statistic
		dataType: double
		summarizeBy: none
		sourceColumn: ks_statistic

	column ks_p_value
		dataType: double
		summarizeBy: none
		sourceColumn: ks_p_value

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status

	partition feature_drift = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/feature_drift.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"feature", type text}, {"psi", type number}, {"ks_statistic", type number}, {"ks_p_value", type number}, {"status", type text}}, "en-CA")
				in
				    Typed
