table model_registry

	column model
		dataType: string
		summarizeBy: none
		sourceColumn: model

	column version
		dataType: int64
		summarizeBy: none
		sourceColumn: version

	column alias
		dataType: string
		summarizeBy: none
		sourceColumn: alias

	column roundtrip_predictions_match
		dataType: boolean
		summarizeBy: none
		sourceColumn: roundtrip_predictions_match

	column git_sha
		dataType: string
		summarizeBy: none
		sourceColumn: git_sha

	column scope
		dataType: string
		summarizeBy: none
		sourceColumn: scope

	column test_auc
		dataType: double
		summarizeBy: none
		sourceColumn: test_auc

	partition model_registry = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/model_registry.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"model", type text}, {"version", Int64.Type}, {"alias", type text}, {"roundtrip_predictions_match", type logical}, {"git_sha", type text}, {"scope", type text}, {"test_auc", type number}}, "en-CA")
				in
				    Typed
