table monthly_performance

	column month
		dataType: string
		summarizeBy: none
		sourceColumn: month

	column trips
		dataType: int64
		summarizeBy: none
		sourceColumn: trips

	column revenue
		dataType: double
		summarizeBy: none
		sourceColumn: revenue

	column savings
		dataType: double
		summarizeBy: none
		sourceColumn: savings

	partition monthly_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/monthly_performance.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"month", type text}, {"trips", Int64.Type}, {"revenue", type number}, {"savings", type number}}, "en-CA")
				in
				    Typed
