table pricing_scenarios

	column zone_id
		dataType: int64
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period

	column price_change
		dataType: double
		summarizeBy: none
		sourceColumn: price_change

	column demand_index
		dataType: double
		summarizeBy: none
		sourceColumn: demand_index

	column revenue_index
		dataType: double
		summarizeBy: none
		sourceColumn: revenue_index

	column elasticity
		dataType: double
		summarizeBy: none
		sourceColumn: elasticity

	partition pricing_scenarios = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/pricing_scenarios.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"zone_id", Int64.Type}, {"period", type text}, {"price_change", type number}, {"demand_index", type number}, {"revenue_index", type number}, {"elasticity", type number}}, "en-CA")
				in
				    Typed
