table quality_gate

	column model
		dataType: string
		summarizeBy: none
		sourceColumn: model

	column passed
		dataType: boolean
		summarizeBy: none
		sourceColumn: passed

	column criteria
		dataType: string
		summarizeBy: none
		sourceColumn: criteria

	column auc
		dataType: double
		summarizeBy: none
		sourceColumn: auc

	column ece
		dataType: double
		summarizeBy: none
		sourceColumn: ece

	column mae
		dataType: double
		summarizeBy: none
		sourceColumn: mae

	column baseline_mae
		dataType: double
		summarizeBy: none
		sourceColumn: baseline_mae

	partition quality_gate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/quality_gate.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"model", type text}, {"passed", type logical}, {"criteria", type text}, {"auc", type number}, {"ece", type number}, {"mae", type number}, {"baseline_mae", type number}}, "en-CA")
				in
				    Typed
