table zone_hour_forecast

	column date
		dataType: string
		summarizeBy: none
		sourceColumn: date

	column zone_id
		dataType: int64
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period

	column baseline_forecast
		dataType: double
		summarizeBy: none
		sourceColumn: baseline_forecast

	column direction
		dataType: string
		summarizeBy: none
		sourceColumn: direction

	column hour
		dataType: int64
		summarizeBy: none
		sourceColumn: hour

	column count
		dataType: int64
		summarizeBy: none
		sourceColumn: count

	column share
		dataType: double
		summarizeBy: none
		sourceColumn: share

	column forecast_trips
		dataType: double
		summarizeBy: none
		sourceColumn: forecast_trips

	column method
		dataType: string
		summarizeBy: none
		sourceColumn: method

	partition zone_hour_forecast = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/zone_hour_forecast.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"date", type text}, {"zone_id", Int64.Type}, {"period", type text}, {"baseline_forecast", type number}, {"direction", type text}, {"hour", Int64.Type}, {"count", Int64.Type}, {"share", type number}, {"forecast_trips", type number}, {"method", type text}}, "en-CA")
				in
				    Typed
