table zone_capacity

	column zone_id
		dataType: int64
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		summarizeBy: none
		sourceColumn: period

	column baseline_forecast
		dataType: double
		summarizeBy: none
		sourceColumn: baseline_forecast

	column daily_capacity
		dataType: double
		summarizeBy: none
		sourceColumn: daily_capacity

	column capacity_trips
		dataType: double
		summarizeBy: none
		sourceColumn: capacity_trips

	column reserve_trips
		dataType: double
		summarizeBy: none
		sourceColumn: reserve_trips

	column available_trips
		dataType: double
		summarizeBy: none
		sourceColumn: available_trips

	column baseline_over_capacity
		dataType: boolean
		summarizeBy: none
		sourceColumn: baseline_over_capacity

	column allocated_trips
		dataType: double
		summarizeBy: none
		sourceColumn: allocated_trips

	column final_utilization
		dataType: double
		summarizeBy: none
		sourceColumn: final_utilization

	column remaining_with_reserve
		dataType: double
		summarizeBy: none
		sourceColumn: remaining_with_reserve

	partition zone_capacity = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/zone_capacity.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"zone_id", Int64.Type}, {"period", type text}, {"baseline_forecast", type number}, {"daily_capacity", type number}, {"capacity_trips", type number}, {"reserve_trips", type number}, {"available_trips", type number}, {"baseline_over_capacity", type logical}, {"allocated_trips", type number}, {"final_utilization", type number}, {"remaining_with_reserve", type number}}, "en-CA")
				in
				    Typed
