table customer_segments
	lineageTag: b861b98c-bec5-5dc1-8ad8-abc2a09000a9

	column rfm_segment
		dataType: string
		lineageTag: 54ae55d3-d504-5ef7-9578-037d48039a77
		summarizeBy: none
		sourceColumn: rfm_segment
		sortByColumn: segment_order

	column zone_id
		dataType: string
		lineageTag: c56f0aa3-56c7-5f91-bef2-1494ec59df55
		summarizeBy: none
		sourceColumn: zone_id

	column tier
		dataType: string
		lineageTag: d544f251-1b02-56d2-a677-8219b6b33546
		summarizeBy: none
		sourceColumn: tier

	column customers
		dataType: int64
		formatString: #,0
		lineageTag: 39f92ba8-2891-575d-ad10-c6812f804fb2
		summarizeBy: sum
		sourceColumn: customers

	column eligible_customers
		dataType: int64
		formatString: #,0
		lineageTag: 95f7a530-230d-5e57-87af-04cc635e9728
		summarizeBy: sum
		sourceColumn: eligible_customers

	column planned_customers
		dataType: int64
		formatString: #,0
		lineageTag: 7a2ecdf3-2176-564d-8580-e186ff90d662
		summarizeBy: sum
		sourceColumn: planned_customers

	column sum_propensity
		dataType: double
		formatString: #,0.00
		lineageTag: 03ea6bfe-2698-566f-8dc7-93ef08189d73
		summarizeBy: sum
		sourceColumn: sum_propensity

	column sum_churn
		dataType: double
		formatString: #,0.00
		lineageTag: f2bd99e7-43d8-5f19-a639-91a26af8562a
		summarizeBy: sum
		sourceColumn: sum_churn

	column active_customers
		dataType: int64
		formatString: #,0
		lineageTag: d5def2c8-89c0-5711-b88a-03928951ed04
		summarizeBy: sum
		sourceColumn: active_customers

	column high_risk_customers
		dataType: int64
		formatString: #,0
		lineageTag: e55d49e0-2a8e-562b-acd9-ef95ec693ded
		summarizeBy: sum
		sourceColumn: high_risk_customers

	column sum_clv
		dataType: double
		formatString: #,0.00
		lineageTag: d7cedf91-f6c3-5673-b852-5d1edada4163
		summarizeBy: sum
		sourceColumn: sum_clv

	column sum_best_value
		dataType: double
		formatString: #,0.00
		lineageTag: 7c823a42-0e54-5fd7-be7e-a3d63405d09f
		summarizeBy: sum
		sourceColumn: sum_best_value

	column segment_order
		dataType: int64
		formatString: #,0
		lineageTag: 2927015c-0ddf-5ab5-89e0-fb2298d25a52
		summarizeBy: sum
		sourceColumn: segment_order

	partition customer_segments = m
		mode: import
		source =
				let
				    Source = #table(type table [#"rfm_segment" = nullable text, #"zone_id" = nullable text, #"tier" = nullable text, #"customers" = nullable text, #"eligible_customers" = nullable text, #"planned_customers" = nullable text, #"sum_propensity" = nullable text, #"sum_churn" = nullable text, #"active_customers" = nullable text, #"high_risk_customers" = nullable text, #"sum_clv" = nullable text, #"sum_best_value" = nullable text, #"segment_order" = nullable text], {
				        {"At risk", "0", "Gold", "108", "79", "35", "61.7323", "41.8161", "72", "43", "5913.9826", "1478.3931", "5"},
				        {"At risk", "0", "Platinum", "39", "28", "20", "6.6681", "18.664", "22", "22", "2311.1797", "667.574", "5"},
				        {"At risk", "0", "Silver", "268", "172", "48", "182.3708", "23.9815", "144", "3", "12772.3663", "3334.9399", "5"},
				        {"At risk", "1", "Gold", "110", "74", "15", "63.4306", "44.9752", "76", "44", "5923.4833", "1463.5683", "5"},
				        {"At risk", "1", "Platinum", "31", "23", "15", "5.9608", "14.9834", "18", "18", "1346.2551", "506.1121", "5"},
				        {"At risk", "1", "Silver", "293", "196", "34", "201.9242", "32.416", "172", "4", "13239.4383", "3644.3644", "5"},
				        {"At risk", "2", "Gold", "99", "74", "22", "57.5807", "32.9644", "62", "36", "5389.724", "1300.8901", "5"},
				        {"At risk", "2", "Platinum", "36", "23", "15", "7.8338", "21.5891", "27", "26", "2761.7309", "591.9901", "5"},
				        {"At risk", "2", "Silver", "269", "176", "47", "179.4838", "27.2385", "140", "3", "11912.5623", "3559.0065", "5"},
				        {"At risk", "3", "Gold", "124", "79", "34", "75.0228", "39.9575", "79", "40", "7178.2638", "1836.094", "5"},
				        {"At risk", "3", "Platinum", "32", "22", "14", "5.52", "14.3399", "17", "16", "1657.7201", "544.4428", "5"},
				        {"At risk", "3", "Silver", "286", "205", "70", "190.9364", "27.3454", "148", "1", "13694.7653", "3958.5935", "5"},
				        {"At risk", "4", "Gold", "114", "77", "27", "66.668", "45.5576", "80", "48", "6680.2693", "1576.3037", "5"},
				        {"At risk", "4", "Platinum", "42", "30", "20", "10.2042", "20.3215", "26", "22", "2525.9927", "718.8893", "5"},
				        {"At risk", "4", "Silver", "245", "166", "68", "161.172", "21.3287", "115", "2", "11253.822", "3694.9984", "5"},
				        {"At risk", "5", "Gold", "106", "69", "34", "61.8068", "41.6691", "71", "46", "5648.5419", "1754.0187", "5"},
				        {"At risk", "5", "Platinum", "35", "26", "20", "8.1462", "13.575", "17", "16", "1307.6262", "743.7704", "5"},
				        {"At risk", "5", "Silver", "299", "207", "77", "199.5913", "30.9965", "158", "3", "14928.0644", "4334.0471", "5"},
				        {"Champions", "0", "Gold", "181", "126", "12", "179.3891", "1.4584", "181", "0", "100357.255", "1827.8329", "1"},
				        {"Champions", "0", "Platinum", "554", "366", "264", "549.2505", "5.0484", "554", "4", "693488.8124", "16339.9268", "1"},
				        {"Champions", "0", "Silver", "1", "1", "0", "0.9974", "0.0004", "1", "0", "448.6526", "6.7017", "1"},
				        {"Champions", "1", "Gold", "163", "112", "9", "161.7379", "0.9217", "163", "0", "94665.7236", "1568.2623", "1"},
				        {"Champions", "1", "Platinum", "603", "401", "232", "597.0296", "6.206", "603", "4", "733330.093", "16135.5784", "1"},
				        {"Champions", "1", "Silver", "2", "1", "0", "1.9867", "0.0058", "2", "0", "751.7025", "7.9028", "1"},
				        {"Champions", "2", "Gold", "150", "103", "15", "149.2373", "0.7225", "150", "0", "90204.9731", "1559.2607", "1"},
				        {"Champions", "2", "Platinum", "581", "399", "262", "575.0714", "5.8301", "581", "4", "732340.1265", "15012.3655", "1"},
				        {"Champions", "2", "Silver", "2", "0", "0", "1.9974", "0.0021", "2", "0", "1418.7412", "26.0282", "1"},
				        {"Champions", "3", "Gold", "121", "79", "12", "119.2267", "1.7047", "121", "1", "73756.7909", "1354.0904", "1"},
				        {"Champions", "3", "Platinum", "612", "411", "288", "604.3696", "8.2732", "612", "6", "802282.0929", "16995.5033", "1"},
				        {"Champions", "3", "Silver", "1", "0", "0", "0.9975", "0.0014", "1", "0", "851.5239", "17.2763", "1"},
				        {"Champions", "4", "Gold", "116", "77", "10", "115.3514", "0.5317", "116", "0", "73891.199", "1337.1865", "1"},
				        {"Champions", "4", "Platinum", "626", "427", "267", "619.757", "7.0872", "626", "3", "776330.109", "15415.7542", "1"},
				        {"Champions", "5", "Gold", "103", "67", "3", "102.1636", "0.6149", "103", "0", "65020.9649", "1130.8853", "1"},
				        {"Champions", "5", "Platinum", "609", "409", "247", "601.3864", "8.5645", "609", "3", "739853.4687", "16746.5963", "1"},
				        {"Dormant", "0", "Gold", "204", "134", "99", "77.145", "0.0", "0", "0", "0.0", "2994.2488", "6"},
				        {"Dormant", "0", "Platinum", "45", "28", "23", "8.2044", "0.0", "0", "0", "0.0", "785.6294", "6"},
				        {"Dormant", "0", "Silver", "460", "309", "227", "195.7107", "0.0", "0", "0", "0.0", "6790.0044", "6"},
				        {"Dormant", "1", "Gold", "191", "131", "32", "71.8768", "0.0", "0", "0", "0.0", "2784.8463", "6"},
				        {"Dormant", "1", "Platinum", "61", "42", "33", "11.9285", "0.0", "0", "0", "0.0", "1047.6313", "6"},
				        {"Dormant", "1", "Silver", "498", "325", "102", "209.8657", "0.0", "0", "0", "0.0", "7333.3974", "6"},
				        {"Dormant", "2", "Gold", "196", "130", "88", "72.6579", "0.0", "0", "0", "0.0", "2809.378", "6"},
				        {"Dormant", "2", "Platinum", "59", "42", "35", "11.2372", "0.0", "0", "0", "0.0", "1041.1266", "6"},
				        {"Dormant", "2", "Silver", "507", "346", "236", "211.0246", "0.0", "0", "0", "0.0", "7338.0965", "6"},
				        {"Dormant", "3", "Gold", "195", "139", "97", "70.9518", "0.0", "0", "0", "0.0", "2823.9144", "6"},
				        {"Dormant", "3", "Platinum", "65", "47", "39", "11.5216", "0.0", "0", "0", "0.0", "1180.9422", "6"},
				        {"Dormant", "3", "Silver", "453", "289", "206", "183.6905", "0.0", "0", "0", "0.0", "6654.8038", "6"},
				        {"Dormant", "4", "Gold", "208", "143", "101", "78.5851", "0.0", "0", "0", "0.0", "3064.497", "6"},
				        {"Dormant", "4", "Platinum", "57", "35", "27", "10.1825", "0.0", "0", "0", "0.0", "940.2723", "6"},
				        {"Dormant", "4", "Silver", "469", "318", "230", "186.7922", "0.0", "0", "0", "0.0", "6905.6684", "6"},
				        {"Dormant", "5", "Gold", "241", "159", "107", "91.544", "0.0", "0", "0", "0.0", "3467.0592", "6"},
				        {"Dormant", "5", "Platinum", "61", "36", "31", "12.0699", "0.0", "0", "0", "0.0", "1066.1967", "6"},
				        {"Dormant", "5", "Silver", "440", "318", "212", "179.0117", "0.0", "0", "0", "0.0", "6357.8626", "6"},
				        {"Loyal", "0", "Gold", "922", "652", "16", "883.4886", "35.2707", "922", "3", "276921.7848", "7263.4001", "2"},
				        {"Loyal", "0", "Platinum", "81", "57", "24", "75.3838", "8.1282", "81", "6", "39978.8518", "1464.7905", "2"},
				        {"Loyal", "0", "Silver", "339", "232", "3", "308.2813", "10.9002", "339", "0", "62846.9491", "2494.0736", "2"},
				        {"Loyal", "1", "Gold", "972", "663", "15", "927.2108", "41.868", "972", "8", "296518.2081", "7294.1977", "2"},
				        {"Loyal", "1", "Platinum", "73", "47", "16", "68.8339", "4.9913", "73", "4", "38714.1649", "1515.663", "2"},
				        {"Loyal", "1", "Silver", "310", "212", "1", "278.7531", "9.5282", "310", "0", "58199.1572", "2327.425", "2"},
				        {"Loyal", "2", "Gold", "951", "652", "18", "905.6916", "45.5791", "951", "7", "287169.8951", "7366.5174", "2"},
				        {"Loyal", "2", "Platinum", "95", "61", "21", "90.6504", "5.1526", "95", "2", "50857.553", "1640.1622", "2"},
				        {"Loyal", "2", "Silver", "276", "189", "0", "249.3706", "9.1924", "276", "0", "52693.859", "1988.6928", "2"},
				        {"Loyal", "3", "Gold", "930", "631", "19", "887.1759", "37.3795", "930", "9", "288567.0445", "7464.5337", "2"},
				        {"Loyal", "3", "Platinum", "117", "83", "26", "109.2062", "9.0541", "117", "5", "59280.6153", "2097.1793", "2"},
				        {"Loyal", "3", "Silver", "286", "182", "0", "256.1836", "8.7437", "286", "0", "56368.7983", "2301.5203", "2"},
				        {"Loyal", "4", "Gold", "939", "625", "19", "893.8427", "41.653", "939", "7", "291730.9702", "7434.5092", "2"},
				        {"Loyal", "4", "Platinum", "127", "97", "31", "118.7797", "10.3808", "127", "5", "62491.6642", "2174.2418", "2"},
				        {"Loyal", "4", "Silver", "233", "157", "5", "209.4067", "7.102", "233", "0", "48295.5551", "2003.5763", "2"},
				        {"Loyal", "5", "Gold", "1037", "729", "21", "990.3505", "42.1707", "1037", "6", "331012.0636", "9314.8687", "2"},
				        {"Loyal", "5", "Platinum", "130", "89", "32", "121.0068", "8.7082", "130", "6", "67370.9608", "2464.431", "2"},
				        {"Loyal", "5", "Silver", "248", "171", "5", "222.9842", "8.1409", "248", "0", "48371.3238", "2179.2566", "2"},
				        {"Occasional", "0", "Gold", "93", "73", "5", "80.1015", "12.2446", "92", "1", "11061.6393", "1093.7906", "3"},
				        {"Occasional", "0", "Platinum", "4", "2", "2", "2.2518", "1.1625", "3", "1", "280.9495", "84.7267", "3"},
				        {"Occasional", "0", "Silver", "892", "617", "88", "604.9568", "67.9828", "674", "0", "59860.7917", "9963.8817", "3"},
				        {"Occasional", "1", "Gold", "94", "65", "4", "80.7909", "10.9612", "92", "2", "12488.4392", "1133.7344", "3"},
				        {"Occasional", "1", "Platinum", "4", "3", "1", "2.2742", "1.4941", "3", "1", "233.2666", "67.8881", "3"},
				        {"Occasional", "1", "Silver", "816", "560", "43", "558.6375", "61.0283", "624", "0", "57473.366", "9085.021", "3"},
				        {"Occasional", "2", "Gold", "121", "90", "12", "103.6471", "13.0859", "113", "2", "14551.1807", "1552.4359", "3"},
				        {"Occasional", "2", "Platinum", "4", "2", "2", "2.2765", "0.3548", "2", "0", "281.8923", "74.4295", "3"},
				        {"Occasional", "2", "Silver", "789", "542", "83", "538.0874", "63.7192", "599", "0", "55554.4755", "9262.36", "3"},
				        {"Occasional", "3", "Gold", "144", "108", "11", "125.9417", "16.042", "141", "3", "19128.4678", "1741.2135", "3"},
				        {"Occasional", "3", "Platinum", "3", "3", "2", "1.1892", "1.7329", "2", "2", "84.1239", "43.1353", "3"},
				        {"Occasional", "3", "Silver", "782", "531", "92", "520.6714", "63.5638", "579", "0", "56338.0863", "9400.8854", "3"},
				        {"Occasional", "4", "Gold", "108", "69", "11", "91.6391", "13.5173", "104", "0", "12902.6451", "1310.5905", "3"},
				        {"Occasional", "4", "Platinum", "4", "4", "3", "2.0131", "2.0534", "4", "2", "323.3471", "70.4513", "3"},
				        {"Occasional", "4", "Silver", "776", "541", "86", "523.8822", "61.4811", "581", "0", "56786.1766", "9635.6925", "3"},
				        {"Occasional", "5", "Gold", "138", "96", "10", "119.3127", "14.9094", "133", "0", "18457.9644", "1797.7888", "3"},
				        {"Occasional", "5", "Platinum", "4", "3", "2", "1.64", "1.7281", "3", "2", "265.4358", "85.3929", "3"},
				        {"Occasional", "5", "Silver", "787", "545", "110", "534.2738", "63.4242", "595", "1", "58828.2377", "9898.3666", "3"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"rfm_segment", type text}, {"zone_id", type text}, {"tier", type text}, {"customers", Int64.Type}, {"eligible_customers", Int64.Type}, {"planned_customers", Int64.Type}, {"sum_propensity", type number}, {"sum_churn", type number}, {"active_customers", Int64.Type}, {"high_risk_customers", Int64.Type}, {"sum_clv", type number}, {"sum_best_value", type number}, {"segment_order", Int64.Type}})
				in
				    Typed
