table demand_backtest
	lineageTag: 2ebc73c1-cd14-57bb-b5ed-c2096017a290

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8f3971f1-cd9f-5442-aa39-4615bd97f5f2
		summarizeBy: none
		sourceColumn: date

	column period
		dataType: string
		lineageTag: de826848-e332-535a-b640-6e34e798bfe8
		summarizeBy: none
		sourceColumn: period

	column actual
		dataType: double
		formatString: #,0.00
		lineageTag: 6221f7e2-0b87-5daf-8464-c9aefc01bc32
		summarizeBy: sum
		sourceColumn: actual

	column forecast
		dataType: double
		formatString: #,0.00
		lineageTag: 74df4dd0-c11f-5626-abd0-4848234c9841
		summarizeBy: sum
		sourceColumn: forecast

	partition demand_backtest = m
		mode: import
		source =
				let
				    Source = #table(type table [#"date" = nullable text, #"period" = nullable text, #"actual" = nullable text, #"forecast" = nullable text], {
				        {"2025-09-01", "Off-peak", "1417.0", "1411.2713"},
				        {"2025-09-01", "Peak", "1238.0", "1360.5079"},
				        {"2025-09-02", "Off-peak", "2249.0", "2130.0379"},
				        {"2025-09-02", "Peak", "2123.0", "2015.7935"},
				        {"2025-09-03", "Off-peak", "2204.0", "2266.8078"},
				        {"2025-09-03", "Peak", "2089.0", "2191.5422"},
				        {"2025-09-04", "Off-peak", "1734.0", "2190.0646"},
				        {"2025-09-04", "Peak", "1586.0", "2108.531"},
				        {"2025-09-05", "Off-peak", "2105.0", "2310.0937"},
				        {"2025-09-05", "Peak", "1932.0", "2224.457"},
				        {"2025-09-06", "Weekend", "3341.0", "3698.9867"},
				        {"2025-09-07", "Weekend", "3391.0", "3422.0712"},
				        {"2025-09-08", "Off-peak", "2286.0", "2105.0068"},
				        {"2025-09-08", "Peak", "2132.0", "1994.5896"},
				        {"2025-09-09", "Off-peak", "2284.0", "1962.4625"},
				        {"2025-09-09", "Peak", "2109.0", "1860.393"},
				        {"2025-09-10", "Off-peak", "2243.0", "2139.3445"},
				        {"2025-09-10", "Peak", "2018.0", "2049.529"},
				        {"2025-09-11", "Off-peak", "2229.0", "2202.6526"},
				        {"2025-09-11", "Peak", "2167.0", "2125.6631"},
				        {"2025-09-12", "Off-peak", "2324.0", "2344.6715"},
				        {"2025-09-12", "Peak", "2028.0", "2253.6544"},
				        {"2025-09-13", "Weekend", "3467.0", "3752.4203"},
				        {"2025-09-14", "Weekend", "3386.0", "3616.0822"},
				        {"2025-09-15", "Off-peak", "2259.0", "2306.9666"},
				        {"2025-09-15", "Peak", "2014.0", "2197.4733"},
				        {"2025-09-16", "Off-peak", "2308.0", "2177.2902"},
				        {"2025-09-16", "Peak", "1977.0", "2056.9885"},
				        {"2025-09-17", "Off-peak", "2202.0", "2342.3646"},
				        {"2025-09-17", "Peak", "1958.0", "2243.9302"},
				        {"2025-09-18", "Off-peak", "2220.0", "2193.2955"},
				        {"2025-09-18", "Peak", "1969.0", "2116.5819"},
				        {"2025-09-19", "Off-peak", "2204.0", "2333.1891"},
				        {"2025-09-19", "Peak", "2080.0", "2241.3919"},
				        {"2025-09-20", "Weekend", "3495.0", "3817.256"},
				        {"2025-09-21", "Weekend", "3269.0", "3602.1421"},
				        {"2025-09-22", "Off-peak", "2074.0", "2208.8487"},
				        {"2025-09-22", "Peak", "1896.0", "2100.6348"},
				        {"2025-09-23", "Off-peak", "1977.0", "2099.052"},
				        {"2025-09-23", "Peak", "1840.0", "1990.1949"},
				        {"2025-09-24", "Off-peak", "1950.0", "1874.6573"},
				        {"2025-09-24", "Peak", "1862.0", "1794.908"},
				        {"2025-09-25", "Off-peak", "2034.0", "2078.9918"},
				        {"2025-09-25", "Peak", "1943.0", "2014.6739"},
				        {"2025-09-26", "Off-peak", "2162.0", "2390.3555"},
				        {"2025-09-26", "Peak", "1957.0", "2247.8995"},
				        {"2025-09-27", "Weekend", "3250.0", "3782.0577"},
				        {"2025-09-28", "Weekend", "3259.0", "3556.6648"},
				        {"2025-09-29", "Off-peak", "2150.0", "1773.7025"},
				        {"2025-09-29", "Peak", "2101.0", "1689.8291"},
				        {"2025-09-30", "Off-peak", "1266.0", "1338.4864"},
				        {"2025-09-30", "Peak", "1204.0", "1259.9531"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"date", type date}, {"period", type text}, {"actual", type number}, {"forecast", type number}})
				in
				    Typed
