table dim_zone
	lineageTag: d8fccf4e-05b5-5326-a6c2-3323b2a72892

	column zone_id
		dataType: string
		lineageTag: b8a7a087-81ec-5e00-a816-091fb752f961
		summarizeBy: none
		sourceColumn: zone_id

	column zone_name
		dataType: string
		lineageTag: 73c5ea06-00ef-589e-8525-5de81107f86f
		summarizeBy: none
		sourceColumn: zone_name
		sortByColumn: zone_order

	column zone_order
		dataType: int64
		formatString: #,0
		lineageTag: 7fdcf624-072d-5f40-81ef-6a50f7b7956c
		summarizeBy: sum
		sourceColumn: zone_order

	partition dim_zone = m
		mode: import
		source =
				let
				    Source = #table(type table [#"zone_id" = nullable text, #"zone_name" = nullable text, #"zone_order" = nullable text], {
				        {"0", "West", "0"},
				        {"1", "Northwest", "1"},
				        {"2", "Central", "2"},
				        {"3", "Northeast", "3"},
				        {"4", "East", "4"},
				        {"5", "Outer east", "5"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"zone_id", type text}, {"zone_name", type text}, {"zone_order", Int64.Type}})
				in
				    Typed
