table elasticity
	lineageTag: f65505cb-d7f7-5f2e-8550-26023a2dc6bf

	column zone_id
		dataType: string
		lineageTag: f2746f20-307f-55b2-8ed7-7e76a6aa4b62
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		lineageTag: 0642423b-f16a-5ee1-a1a1-f9252cefa212
		summarizeBy: none
		sourceColumn: period

	column segment
		dataType: string
		lineageTag: 15347060-128c-5332-8c33-93f408b1e3db
		summarizeBy: none
		sourceColumn: segment

	column elasticity
		dataType: double
		formatString: 0.0%
		lineageTag: 5a64e706-02a2-5164-8018-8627dc5f682c
		summarizeBy: none
		sourceColumn: elasticity

	column ci_low
		dataType: double
		formatString: 0.0%
		lineageTag: 6220b6df-7bc4-538e-9ecf-db82e038bf94
		summarizeBy: none
		sourceColumn: ci_low

	column ci_high
		dataType: double
		formatString: 0.0%
		lineageTag: 338abcd5-b5b1-566e-91f7-51dcd64e53ce
		summarizeBy: none
		sourceColumn: ci_high

	column ols_elasticity
		dataType: double
		formatString: 0.0%
		lineageTag: b3277de5-7e6d-5abe-b607-fac98b677056
		summarizeBy: none
		sourceColumn: ols_elasticity

	partition elasticity = m
		mode: import
		source =
				let
				    Source = #table(type table [#"zone_id" = nullable text, #"period" = nullable text, #"segment" = nullable text, #"elasticity" = nullable text, #"ci_low" = nullable text, #"ci_high" = nullable text, #"ols_elasticity" = nullable text], {
				        {"0", "Off-peak", "Business", "-0.4444", "-0.5674", "-0.3214", "-0.3704"},
				        {"0", "Off-peak", "Personal", "-0.5534", "-0.6293", "-0.4774", "-0.5435"},
				        {"0", "Peak", "Business", "-0.3827", "-0.5032", "-0.2622", "-0.3359"},
				        {"0", "Peak", "Personal", "-0.605", "-0.6663", "-0.5437", "-0.5986"},
				        {"0", "Weekend", "Business", "-0.7062", "-0.83", "-0.5823", "-0.6536"},
				        {"0", "Weekend", "Personal", "-1.0355", "-1.1068", "-0.9643", "-1.0265"},
				        {"1", "Off-peak", "Business", "-0.4745", "-0.5917", "-0.3572", "-0.432"},
				        {"1", "Off-peak", "Personal", "-0.7706", "-0.8442", "-0.697", "-0.7662"},
				        {"1", "Peak", "Business", "-0.4313", "-0.5474", "-0.3151", "-0.4012"},
				        {"1", "Peak", "Personal", "-0.7547", "-0.8131", "-0.6963", "-0.7512"},
				        {"1", "Weekend", "Business", "-0.6866", "-0.8023", "-0.5708", "-0.632"},
				        {"1", "Weekend", "Personal", "-1.1496", "-1.2188", "-1.0804", "-1.1441"},
				        {"2", "Off-peak", "Business", "-0.4787", "-0.5884", "-0.369", "-0.4467"},
				        {"2", "Off-peak", "Personal", "-0.8835", "-0.9568", "-0.8102", "-0.8815"},
				        {"2", "Peak", "Business", "-0.512", "-0.6275", "-0.3965", "-0.5031"},
				        {"2", "Peak", "Personal", "-0.8809", "-0.9374", "-0.8243", "-0.8795"},
				        {"2", "Weekend", "Business", "-0.7012", "-0.8079", "-0.5946", "-0.6667"},
				        {"2", "Weekend", "Personal", "-1.2833", "-1.3503", "-1.2164", "-1.2814"},
				        {"3", "Off-peak", "Business", "-0.594", "-0.7057", "-0.4823", "-0.6265"},
				        {"3", "Off-peak", "Personal", "-1.0136", "-1.0768", "-0.9504", "-1.0143"},
				        {"3", "Peak", "Business", "-0.4932", "-0.5916", "-0.3948", "-0.4839"},
				        {"3", "Peak", "Personal", "-1.0075", "-1.0623", "-0.9528", "-1.0079"},
				        {"3", "Weekend", "Business", "-0.8081", "-0.9194", "-0.6968", "-0.8318"},
				        {"3", "Weekend", "Personal", "-1.4298", "-1.4954", "-1.3641", "-1.4314"},
				        {"4", "Off-peak", "Business", "-0.6136", "-0.7188", "-0.5085", "-0.6502"},
				        {"4", "Off-peak", "Personal", "-1.1266", "-1.1884", "-1.0648", "-1.129"},
				        {"4", "Peak", "Business", "-0.696", "-0.787", "-0.6051", "-0.7177"},
				        {"4", "Peak", "Personal", "-1.1206", "-1.1703", "-1.0708", "-1.1222"},
				        {"4", "Weekend", "Business", "-0.8341", "-0.9436", "-0.7247", "-0.8711"},
				        {"4", "Weekend", "Personal", "-1.5201", "-1.5839", "-1.4563", "-1.5236"},
				        {"5", "Off-peak", "Business", "-0.5818", "-0.6846", "-0.479", "-0.6017"},
				        {"5", "Off-peak", "Personal", "-1.2555", "-1.3163", "-1.1947", "-1.2597"},
				        {"5", "Peak", "Business", "-0.6287", "-0.7197", "-0.5377", "-0.6406"},
				        {"5", "Peak", "Personal", "-1.2512", "-1.298", "-1.2044", "-1.254"},
				        {"5", "Weekend", "Business", "-0.8479", "-0.953", "-0.7427", "-0.8874"},
				        {"5", "Weekend", "Personal", "-1.5974", "-1.6554", "-1.5394", "-1.6017"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"zone_id", type text}, {"period", type text}, {"segment", type text}, {"elasticity", type number}, {"ci_low", type number}, {"ci_high", type number}, {"ols_elasticity", type number}})
				in
				    Typed
