table experiment_effects
	lineageTag: 5bae5e06-0358-5299-a37d-c3c90b0dc7c8

	column offer_id
		dataType: string
		lineageTag: 2a654281-8aa0-5b3a-9412-38531f49ff23
		summarizeBy: none
		sourceColumn: offer_id

	column n
		dataType: int64
		formatString: #,0
		lineageTag: 1ebbb23d-85f9-53d0-bd8a-5826ad075efb
		summarizeBy: sum
		sourceColumn: n

	column trips_effect
		dataType: double
		formatString: #,0.00
		lineageTag: 7b3dc729-6858-59cd-bf2c-0eb5a41ea41b
		summarizeBy: sum
		sourceColumn: trips_effect

	column value_effect
		dataType: double
		formatString: #,0.00
		lineageTag: 52b43603-bb06-5d37-ad36-366cd8a30a30
		summarizeBy: sum
		sourceColumn: value_effect

	column value_low
		dataType: double
		formatString: #,0.00
		lineageTag: e8bddfb9-4147-5026-8b01-026c5e4d6e53
		summarizeBy: sum
		sourceColumn: value_low

	column value_high
		dataType: double
		formatString: #,0.00
		lineageTag: e745d93b-97e6-5f30-b08f-168880891562
		summarizeBy: sum
		sourceColumn: value_high

	column p_adjusted
		dataType: double
		formatString: 0.0%
		lineageTag: a69a64b8-e16b-5515-8b1b-fc7c66966c32
		summarizeBy: none
		sourceColumn: p_adjusted

	column variance_reduction
		dataType: double
		formatString: 0.0%
		lineageTag: 4a2a537e-f87e-5cac-933a-35b9f08de7fe
		summarizeBy: none
		sourceColumn: variance_reduction

	column enrollment_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 79012069-bc61-5014-a556-2e5d4713e9a6
		summarizeBy: none
		sourceColumn: enrollment_rate

	partition experiment_effects = m
		mode: import
		source =
				let
				    Source = #table(type table [#"offer_id" = nullable text, #"n" = nullable text, #"trips_effect" = nullable text, #"value_effect" = nullable text, #"value_low" = nullable text, #"value_high" = nullable text, #"p_adjusted" = nullable text, #"variance_reduction" = nullable text, #"enrollment_rate" = nullable text], {
				        {"rush_hour_25", "2500", "0.6528", "-2.7574", "-4.5729", "-0.942", "0.0002", "0.8241", "0.398"},
				        {"offpeak_15", "2500", "0.5706", "-0.8144", "-2.5605", "0.9316", "1.0", "0.8418", "0.39"},
				        {"pct_10", "2500", "0.7845", "-1.341", "-3.2158", "0.5338", "0.4258", "0.8445", "0.42"},
				        {"weekend_20", "2500", "0.489", "-0.6418", "-2.3846", "1.1009", "1.0", "0.847", "0.408"},
				        {"spend_10", "2500", "0.6707", "0.9725", "-0.8475", "2.7925", "1.0", "0.8333", "0.4068"},
				        {"free_trip", "2500", "0.9621", "1.0926", "-0.6219", "2.8071", "0.695", "0.8169", "0.402"},
				        {"offpeak_pass", "2500", "0.2792", "-8.0084", "-9.9467", "-6.07", "0.0", "0.8456", "0.3976"},
				        {"loyalty_500", "2500", "0.2639", "-3.9533", "-5.7493", "-2.1572", "0.0", "0.8452", "0.39"},
				        {"loyalty_1500", "2500", "0.522", "-12.4166", "-14.2255", "-10.6077", "0.0", "0.8346", "0.4124"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"offer_id", type text}, {"n", Int64.Type}, {"trips_effect", type number}, {"value_effect", type number}, {"value_low", type number}, {"value_high", type number}, {"p_adjusted", type number}, {"variance_reduction", type number}, {"enrollment_rate", type number}})
				in
				    Typed
