table feed_quality
	lineageTag: f8b69db4-e478-5a16-b432-9af023125a31

	column day
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b8e7ffca-9bf2-561e-97ea-7344045fd8de
		summarizeBy: none
		sourceColumn: day

	column rows
		dataType: int64
		formatString: #,0
		lineageTag: 30098811-6e9e-58b9-8f95-e6e78004adf8
		summarizeBy: sum
		sourceColumn: rows

	column expected_rows
		dataType: double
		formatString: #,0.00
		lineageTag: 9fc9d93b-a5ff-5605-98ee-b60da9c19fa6
		summarizeBy: sum
		sourceColumn: expected_rows

	column volume_z
		dataType: double
		formatString: 0.0%
		lineageTag: 10fe6a67-8828-5750-a5e9-c975908c2675
		summarizeBy: none
		sourceColumn: volume_z

	column flagged
		dataType: boolean
		lineageTag: 5a51dd9c-899a-58ac-a2b2-b029a7d2f853
		summarizeBy: none
		sourceColumn: flagged

	column reason
		dataType: string
		lineageTag: 97686091-233a-593e-a202-230cde880dac
		summarizeBy: none
		sourceColumn: reason

	partition feed_quality = m
		mode: import
		source =
				let
				    Source = #table(type table [#"day" = nullable text, #"rows" = nullable text, #"expected_rows" = nullable text, #"volume_z" = nullable text, #"flagged" = nullable text, #"reason" = nullable text], {
				        {"2025-06-01", "4695", "4919.5", "-1.924", "False", null},
				        {"2025-06-02", "6014", "4901.5", "3.9037", "False", null},
				        {"2025-06-03", "6051", "5985.5", "-0.6222", "False", null},
				        {"2025-06-04", "6011", "5749.5", "0.3394", "False", null},
				        {"2025-06-05", "4198", "5852.0", "-0.5624", "False", null},
				        {"2025-06-06", "5804", "6109.0", "-1.9852", "False", null},
				        {"2025-06-07", "4500", "4724.0", "-1.5705", "False", null},
				        {"2025-06-08", "4622", "4810.0", "-1.7642", "False", null},
				        {"2025-06-09", "5458", "6056.0", "-1.8498", "False", null},
				        {"2025-06-10", "5843", "6027.5", "-1.4707", "False", null},
				        {"2025-06-11", "5776", "5693.5", "-0.4962", "False", null},
				        {"2025-06-12", "5704", "4749.5", "3.403", "False", null},
				        {"2025-06-13", "5758", "6016.0", "-1.901", "False", null},
				        {"2025-06-14", "4475", "4582.0", "-1.4288", "False", null},
				        {"2025-06-15", "4601", "4658.5", "-1.1668", "False", null},
				        {"2025-06-16", "5722", "5736.0", "-0.9337", "False", null},
				        {"2025-06-17", "5795", "6027.5", "-1.4869", "False", null},
				        {"2025-06-18", "5011", "5576.0", "-0.6369", "False", null},
				        {"2025-06-19", "5007", "4749.5", "2.6523", "False", null},
				        {"2025-06-20", "5519", "5893.5", "-2.1461", "False", null},
				        {"2025-06-21", "4058", "4582.0", "-1.4195", "False", null},
				        {"2025-06-22", "4273", "4611.5", "-2.0844", "False", null},
				        {"2025-06-23", "5612", "5868.0", "-1.919", "False", null},
				        {"2025-06-24", "5372", "5923.5", "-2.8074", "False", null},
				        {"2025-06-25", "5333", "5576.0", "-1.9179", "False", null},
				        {"2025-06-26", "5478", "5154.0", "0.5482", "False", null},
				        {"2025-06-27", "4214", "5781.0", "-2.395", "False", null},
				        {"2025-06-28", "4022", "4487.5", "-2.2442", "False", null},
				        {"2025-06-29", "4209", "4611.5", "-3.0108", "False", null},
				        {"2025-06-30", "5298", "5667.0", "-1.3908", "False", null},
				        {"2025-07-01", "3249", "5819.0", "-2.8231", "False", null},
				        {"2025-07-02", "5246", "5554.5", "-1.9472", "False", null},
				        {"2025-07-03", "4917", "5242.5", "-0.6974", "False", null},
				        {"2025-07-04", "5279", "5638.5", "-2.4162", "False", null},
				        {"2025-07-05", "4112", "4266.5", "-1.6502", "False", null},
				        {"2025-07-06", "4142", "4437.0", "-2.4843", "False", null},
				        {"2025-07-07", "5183", "5535.0", "-2.4122", "False", null},
				        {"2025-07-08", "5211", "5583.5", "-2.4901", "False", null},
				        {"2025-07-09", "4851", "5289.5", "-1.1776", "False", null},
				        {"2025-07-10", "5116", "5242.5", "-1.4033", "False", null},
				        {"2025-07-11", "5052", "5399.0", "-2.429", "False", null},
				        {"2025-07-12", "4075", "4085.0", "-0.4484", "False", null},
				        {"2025-07-13", "3855", "4241.0", "-2.5328", "False", null},
				        {"2025-07-14", "5112", "5455.0", "-2.3943", "False", null},
				        {"2025-07-15", "4910", "5291.5", "-2.6253", "False", null},
				        {"2025-07-16", "5030", "5128.5", "-0.8884", "False", null},
				        {"2025-07-17", "5020", "5061.5", "-0.9366", "False", null},
				        {"2025-07-18", "4914", "5165.5", "-2.043", "False", null},
				        {"2025-07-19", "3914", "4066.5", "-1.7698", "False", null},
				        {"2025-07-20", "3790", "4175.5", "-2.0368", "False", null},
				        {"2025-07-21", "4983", "5240.5", "-2.0541", "False", null},
				        {"2025-07-22", "5015", "5060.5", "-1.0877", "False", null},
				        {"2025-07-23", "1985", "5138.0", "-23.0991", "True", "volume vs same weekday"},
				        {"2025-07-24", "7575", "5068.0", "9.8401", "True", "volume vs same weekday"},
				        {"2025-07-25", "4741", "4983.0", "-1.1573", "False", null},
				        {"2025-07-26", "3793", "4048.5", "-1.6055", "False", null},
				        {"2025-07-27", "3367", "3998.5", "-1.4949", "False", null},
				        {"2025-07-28", "4743", "5147.5", "-2.7892", "False", null},
				        {"2025-07-29", "4952", "4962.5", "-0.9261", "False", null},
				        {"2025-07-30", "4568", "4940.5", "-2.0465", "False", null},
				        {"2025-07-31", "4495", "5068.0", "-1.606", "False", null},
				        {"2025-08-01", "4820", "4983.0", "-1.6538", "False", null},
				        {"2025-08-02", "3675", "3994.5", "-2.8247", "False", null},
				        {"2025-08-03", "3726", "3822.5", "-1.4741", "False", null},
				        {"2025-08-04", "2887", "5047.5", "-2.2594", "False", null},
				        {"2025-08-05", "4632", "4983.5", "-2.5859", "False", null},
				        {"2025-08-06", "4661", "4709.5", "-1.1185", "False", null},
				        {"2025-08-07", "4710", "5068.0", "-2.5886", "False", null},
				        {"2025-08-08", "4642", "4867.0", "-1.9827", "False", null},
				        {"2025-08-09", "3767", "3853.5", "-1.4071", "False", null},
				        {"2025-08-10", "3656", "3758.0", "-1.5196", "False", null},
				        {"2025-08-11", "4663", "4863.0", "-1.858", "False", null},
				        {"2025-08-12", "4341", "4931.0", "-2.354", "False", null},
				        {"2025-08-13", "4568", "4614.5", "-0.8043", "False", null},
				        {"2025-08-14", "4615", "4865.0", "-2.1094", "False", null},
				        {"2025-08-15", "4543", "4780.5", "-2.0674", "False", null},
				        {"2025-08-16", "3705", "3780.0", "-1.3449", "False", null},
				        {"2025-08-17", "3085", "3691.0", "-2.1985", "False", null},
				        {"2025-08-18", "4638", "4703.0", "-1.2018", "False", null},
				        {"2025-08-19", "2191", "4792.0", "-1.95", "False", null},
				        {"2025-08-20", "3968", "4568.0", "-0.857", "False", null},
				        {"2025-08-21", "4548", "4662.5", "-1.4576", "True", "out-of-range values"},
				        {"2025-08-22", "4435", "4691.5", "-2.1905", "False", null},
				        {"2025-08-23", "3527", "3736.0", "-1.9129", "False", null},
				        {"2025-08-24", "3427", "3511.5", "-1.1368", "False", null},
				        {"2025-08-25", "4313", "4650.5", "-2.6372", "False", null},
				        {"2025-08-26", "3989", "4486.5", "-1.637", "False", null},
				        {"2025-08-27", "4326", "4568.0", "-2.1486", "False", null},
				        {"2025-08-28", "3757", "4581.5", "-1.7173", "False", null},
				        {"2025-08-29", "4392", "4592.5", "-1.9198", "False", null},
				        {"2025-08-30", "3449", "3690.0", "-2.4549", "False", null},
				        {"2025-08-31", "3492", "3541.5", "-1.2055", "False", null},
				        {"2025-09-01", "2656", "4475.5", "-1.3972", "False", null},
				        {"2025-09-02", "4372", "4165.0", "0.2569", "False", null},
				        {"2025-09-03", "4293", "4447.0", "-1.7002", "False", null},
				        {"2025-09-04", "3320", "4581.5", "-2.4", "False", null},
				        {"2025-09-05", "4037", "4489.0", "-2.2091", "False", null},
				        {"2025-09-06", "3341", "3616.0", "-2.7249", "False", null},
				        {"2025-09-07", "3391", "3459.5", "-1.1674", "False", null},
				        {"2025-09-08", "4418", "4475.5", "-1.1788", "False", null},
				        {"2025-09-09", "4393", "4165.0", "0.3689", "False", null},
				        {"2025-09-10", "6761", "4309.5", "9.6479", "True", "duplicate natural keys"},
				        {"2025-09-11", "4396", "4152.5", "0.4551", "False", null},
				        {"2025-09-12", "4352", "4413.5", "-1.2045", "False", null},
				        {"2025-09-13", "3467", "3488.0", "-0.8853", "False", null},
				        {"2025-09-14", "3387", "3409.0", "-0.7631", "False", null},
				        {"2025-09-15", "4275", "4365.5", "-1.3661", "False", null},
				        {"2025-09-16", "4285", "4180.5", "-0.2996", "False", null},
				        {"2025-09-17", "4160", "4309.5", "-1.7017", "False", null},
				        {"2025-09-18", "4190", "4076.5", "-0.1907", "False", null},
				        {"2025-09-19", "4284", "4372.0", "-1.3518", "False", null},
				        {"2025-09-20", "3495", "3458.0", "-0.6279", "False", null},
				        {"2025-09-21", "3270", "3409.0", "-0.6135", "False", null},
				        {"2025-09-22", "3970", "4294.0", "-1.3858", "False", null},
				        {"2025-09-23", "3818", "4328.5", "-1.2934", "False", null},
				        {"2025-09-24", "3813", "4309.5", "-1.5743", "False", null},
				        {"2025-09-25", "3977", "3973.5", "0.2915", "False", null},
				        {"2025-09-26", "4119", "4318.0", "-1.9792", "False", null},
				        {"2025-09-27", "3251", "3458.0", "-2.319", "False", null},
				        {"2025-09-28", "3259", "3389.0", "-1.7906", "False", null},
				        {"2025-09-29", "4251", "4122.5", "-0.1593", "False", null},
				        {"2025-09-30", "2470", "4328.5", "-2.3132", "False", null}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"day", type date}, {"rows", Int64.Type}, {"expected_rows", type number}, {"volume_z", type number}, {"flagged", type logical}, {"reason", type text}})
				in
				    Typed
