table learner_comparison
	lineageTag: 3e8027e9-a004-5598-bffa-cf9219b5e5cf

	column offer_id
		dataType: string
		lineageTag: c81b3eb6-eeac-5d6e-9958-9c01d5ad9a37
		summarizeBy: none
		sourceColumn: offer_id

	column learner
		dataType: string
		lineageTag: ce4b5916-f226-502c-adbc-63fe265d147c
		summarizeBy: none
		sourceColumn: learner

	column value_spearman
		dataType: double
		formatString: 0.0%
		lineageTag: e61caaec-ecaa-5a36-9e6f-a013dc83f761
		summarizeBy: none
		sourceColumn: value_spearman

	column qini
		dataType: double
		formatString: #,0.00
		lineageTag: 584c36d1-8774-564e-a0ab-6e06cb1117ea
		summarizeBy: sum
		sourceColumn: qini

	column selected
		dataType: boolean
		lineageTag: 140abbe5-d23c-5638-8af2-7ea2cc36301b
		summarizeBy: none
		sourceColumn: selected

	partition learner_comparison = m
		mode: import
		source =
				let
				    Source = #table(type table [#"offer_id" = nullable text, #"learner" = nullable text, #"value_spearman" = nullable text, #"qini" = nullable text, #"selected" = nullable text], {
				        {"rush_hour_25", "S-learner", "0.2268", "1.6242", "True"},
				        {"rush_hour_25", "T-learner", "0.0893", "-1.0543", "False"},
				        {"rush_hour_25", "X-learner", "0.1961", "-0.0982", "False"},
				        {"rush_hour_25", "DR-learner", "0.1723", "-0.6201", "False"},
				        {"offpeak_15", "S-learner", "0.0807", "0.0659", "True"},
				        {"offpeak_15", "T-learner", "0.0774", "-1.1194", "False"},
				        {"offpeak_15", "X-learner", "-0.0112", "-0.8698", "False"},
				        {"offpeak_15", "DR-learner", "0.0003", "0.4774", "False"},
				        {"pct_10", "S-learner", "-0.4998", "-1.5072", "True"},
				        {"pct_10", "T-learner", "0.0377", "-2.0666", "False"},
				        {"pct_10", "X-learner", "0.1014", "1.7819", "False"},
				        {"pct_10", "DR-learner", "0.0711", "-1.8932", "False"},
				        {"weekend_20", "S-learner", "-0.164", "0.0255", "True"},
				        {"weekend_20", "T-learner", "-0.0068", "1.169", "False"},
				        {"weekend_20", "X-learner", "-0.09", "0.9742", "False"},
				        {"weekend_20", "DR-learner", "-0.0083", "-0.1047", "False"},
				        {"spend_10", "S-learner", "0.0106", "-1.6419", "True"},
				        {"spend_10", "T-learner", "0.2326", "-1.1343", "False"},
				        {"spend_10", "X-learner", "0.4835", "-1.1107", "False"},
				        {"spend_10", "DR-learner", "0.3051", "-1.4853", "False"},
				        {"free_trip", "S-learner", "0.8443", "2.7896", "True"},
				        {"free_trip", "T-learner", "0.5957", "1.0694", "False"},
				        {"free_trip", "X-learner", "0.8161", "2.9136", "False"},
				        {"free_trip", "DR-learner", "0.8", "2.8977", "False"},
				        {"offpeak_pass", "S-learner", "0.417", "3.8479", "True"},
				        {"offpeak_pass", "T-learner", "0.3967", "3.4387", "False"},
				        {"offpeak_pass", "X-learner", "0.5211", "4.1012", "False"},
				        {"offpeak_pass", "DR-learner", "0.4314", "3.7133", "False"},
				        {"loyalty_500", "S-learner", "-0.4017", "-1.8662", "True"},
				        {"loyalty_500", "T-learner", "0.14", "-0.4414", "False"},
				        {"loyalty_500", "X-learner", "0.2757", "-1.8844", "False"},
				        {"loyalty_500", "DR-learner", "0.2009", "-1.3795", "False"},
				        {"loyalty_1500", "S-learner", "0.4577", "1.3554", "True"},
				        {"loyalty_1500", "T-learner", "0.2247", "-0.7214", "False"},
				        {"loyalty_1500", "X-learner", "0.3422", "-0.9095", "False"},
				        {"loyalty_1500", "DR-learner", "0.1896", "0.4831", "False"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"offer_id", type text}, {"learner", type text}, {"value_spearman", type number}, {"qini", type number}, {"selected", type logical}})
				in
				    Typed
