table monthly_trips
	lineageTag: b1861b51-3822-5955-9c09-2889d5102c91

	column month_label
		dataType: string
		lineageTag: 63482975-8673-5919-81e4-7c3e3b36986e
		summarizeBy: none
		sourceColumn: month_label
		sortByColumn: month_index

	column month_index
		dataType: int64
		formatString: 0
		lineageTag: 345e09e7-6ae0-5e99-8023-bc0aa0de63bd
		summarizeBy: none
		sourceColumn: month_index

	column trips
		dataType: int64
		formatString: #,0
		lineageTag: e10a4284-e618-5075-801d-d75f10ea8d88
		summarizeBy: sum
		sourceColumn: trips

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 75379c1b-bbdf-551a-bcdb-a143915ba9f4
		summarizeBy: sum
		sourceColumn: revenue

	column savings
		dataType: double
		formatString: #,0.00
		lineageTag: 7c414bb8-f5c7-56a1-acfe-609cb7b28579
		summarizeBy: sum
		sourceColumn: savings

	column customers
		dataType: int64
		formatString: #,0
		lineageTag: 720b5c9f-a99a-53e3-9e45-34adf2e5c868
		summarizeBy: sum
		sourceColumn: customers

	column peak_trips
		dataType: int64
		formatString: #,0
		lineageTag: d052c9f3-0bee-5732-ae3f-4ac1ed5952b9
		summarizeBy: sum
		sourceColumn: peak_trips

	partition monthly_trips = m
		mode: import
		source =
				let
				    Source = #table(type table [#"month_label" = nullable text, #"month_index" = nullable text, #"trips" = nullable text, #"revenue" = nullable text, #"savings" = nullable text, #"customers" = nullable text, #"peak_trips" = nullable text], {
				        {"Jan 2024", "1", "154121", "1222434.9023", "22428.1656", "19223", "57395"},
				        {"Feb 2024", "2", "162379", "1289656.3741", "23708.3866", "19629", "59711"},
				        {"Mar 2024", "3", "177088", "1404649.0833", "25957.5756", "20087", "61909"},
				        {"Apr 2024", "4", "169565", "1345577.7933", "24505.1004", "20288", "62259"},
				        {"May 2024", "5", "176682", "1398920.2651", "25784.6101", "20659", "66784"},
				        {"Jun 2024", "6", "162737", "1290176.3834", "23442.4526", "20643", "56403"},
				        {"Jul 2024", "7", "158387", "1257748.3413", "23234.9964", "20957", "59185"},
				        {"Aug 2024", "8", "148662", "1179275.6744", "21971.0121", "20979", "53982"},
				        {"Sep 2024", "9", "136595", "1081668.1964", "19948.8302", "20962", "48350"},
				        {"Oct 2024", "10", "148621", "1182239.9397", "21526.2776", "21589", "55934"},
				        {"Nov 2024", "11", "153594", "1220488.9527", "22399.5292", "21909", "55390"},
				        {"Dec 2024", "12", "162769", "1291002.8459", "23572.7669", "22179", "59414"},
				        {"Jan 2025", "13", "183983", "1508680.1574", "27857.795", "22326", "69268"},
				        {"Feb 2025", "14", "166798", "1368046.6304", "25093.7445", "21697", "61593"},
				        {"Mar 2025", "15", "189435", "1551437.6712", "28426.7857", "21599", "67101"},
				        {"Apr 2025", "16", "179267", "1469304.045", "27115.8929", "21030", "67081"},
				        {"May 2025", "17", "165237", "1351784.8187", "24949.1482", "20279", "59512"},
				        {"Jun 2025", "18", "154428", "1261772.9166", "23155.5208", "19678", "55371"},
				        {"Jul 2025", "19", "143193", "1174620.4938", "21634.3382", "19072", "54073"},
				        {"Aug 2025", "20", "123613", "1011674.3558", "18453.0996", "18179", "42506"},
				        {"Sep 2025", "21", "114962", "942268.7821", "17325.4028", "17417", "42223"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"month_label", type text}, {"month_index", Int64.Type}, {"trips", Int64.Type}, {"revenue", type number}, {"savings", type number}, {"customers", Int64.Type}, {"peak_trips", Int64.Type}})
				in
				    Typed
