table plan_summary
	lineageTag: 84e64996-82ef-52ca-9412-5fdb0ecc2cc7

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: 0ee786c5-fc7d-5d9a-93f7-4bf2ff3ce5d8
		summarizeBy: sum
		sourceColumn: budget

	column contact_limit
		dataType: int64
		formatString: #,0
		lineageTag: a6a03d67-e6fc-53fc-998f-15b5165aeafb
		summarizeBy: sum
		sourceColumn: contact_limit

	column points_limit
		dataType: int64
		formatString: #,0
		lineageTag: 65dfc17b-4973-5952-aff8-a2e9ef39011c
		summarizeBy: sum
		sourceColumn: points_limit

	column eligible_customers
		dataType: int64
		formatString: #,0
		lineageTag: 741ac5b4-3651-5e6a-91e2-0593893df778
		summarizeBy: sum
		sourceColumn: eligible_customers

	column proven_optimal
		dataType: boolean
		lineageTag: 32c99bc0-012e-5487-90b5-b5a5da91b443
		summarizeBy: none
		sourceColumn: proven_optimal

	column decision_variables
		dataType: int64
		formatString: #,0
		lineageTag: b9657e49-73ec-5634-b2eb-464302f4a81e
		summarizeBy: sum
		sourceColumn: decision_variables

	column free_variables
		dataType: int64
		formatString: #,0
		lineageTag: 19029199-6e75-5cc5-894a-cb2e55535367
		summarizeBy: sum
		sourceColumn: free_variables

	column relief_value_per_trip
		dataType: double
		formatString: #,0.00
		lineageTag: c4589a2a-25ff-5a7b-a6dc-1d8cdc7c384a
		summarizeBy: sum
		sourceColumn: relief_value_per_trip

	column min_roi
		dataType: double
		formatString: #,0.00
		lineageTag: b99e5c86-c76d-5cf3-8801-3ed87f982b18
		summarizeBy: sum
		sourceColumn: min_roi

	column required_per_arm
		dataType: int64
		formatString: #,0
		lineageTag: 3a4007ef-6031-5692-84e3-3c01d2c6ded9
		summarizeBy: sum
		sourceColumn: required_per_arm

	partition plan_summary = m
		mode: import
		source =
				let
				    Source = #table(type table [#"budget" = nullable text, #"contact_limit" = nullable text, #"points_limit" = nullable text, #"eligible_customers" = nullable text, #"proven_optimal" = nullable text, #"decision_variables" = nullable text, #"free_variables" = nullable text, #"relief_value_per_trip" = nullable text, #"min_roi" = nullable text, #"required_per_arm" = nullable text], {
				        {"10000.0", "5000", "2500000", "17059", "True", "112563", "4402", "0.5", "0.15", "1794"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"budget", type number}, {"contact_limit", Int64.Type}, {"points_limit", Int64.Type}, {"eligible_customers", Int64.Type}, {"proven_optimal", type logical}, {"decision_variables", Int64.Type}, {"free_variables", Int64.Type}, {"relief_value_per_trip", type number}, {"min_roi", type number}, {"required_per_arm", Int64.Type}})
				in
				    Typed
