table policy_comparison
	lineageTag: 4c346229-de78-527a-abb2-b24b797018ca

	column policy
		dataType: string
		lineageTag: 6814951d-db5f-58f2-8bb8-38066dc06082
		summarizeBy: none
		sourceColumn: policy
		sortByColumn: policy_order

	column policy_order
		dataType: int64
		formatString: #,0
		lineageTag: 07d7eb5f-b5dc-5a9b-8dd4-70e1590c5c8a
		summarizeBy: sum
		sourceColumn: policy_order

	column contacts
		dataType: int64
		formatString: #,0
		lineageTag: 825d71eb-64f8-55e0-8d43-4c549d52fd72
		summarizeBy: sum
		sourceColumn: contacts

	column predicted_value
		dataType: double
		formatString: #,0.00
		lineageTag: 7e00a48d-68f5-5f8c-8aa0-4cdabc1dfb2a
		summarizeBy: sum
		sourceColumn: predicted_value

	column true_value
		dataType: double
		formatString: #,0.00
		lineageTag: b11f631a-6b4a-584c-bcae-d9a2aa2180d2
		summarizeBy: sum
		sourceColumn: true_value

	column true_spend
		dataType: double
		formatString: #,0.00
		lineageTag: 13ea2443-ec7a-5447-a2cc-5f47d3b6439f
		summarizeBy: sum
		sourceColumn: true_spend

	column share_of_oracle
		dataType: double
		formatString: 0.0%
		lineageTag: 3264aad4-ab11-5b26-9293-1910ca1b6d98
		summarizeBy: none
		sourceColumn: share_of_oracle

	column customers_losing_money
		dataType: int64
		formatString: #,0
		lineageTag: 67a2de8b-b6ca-572f-b3fb-21b4bbd49bf6
		summarizeBy: sum
		sourceColumn: customers_losing_money

	partition policy_comparison = m
		mode: import
		source =
				let
				    Source = #table(type table [#"policy" = nullable text, #"policy_order" = nullable text, #"contacts" = nullable text, #"predicted_value" = nullable text, #"true_value" = nullable text, #"true_spend" = nullable text, #"share_of_oracle" = nullable text, #"customers_losing_money" = nullable text], {
				        {"Random targeting", "1", "1943", "-6841.3754", "1106.7269", "10832.5317", "0.0129", "789"},
				        {"Propensity: 10% off top travellers", "2", "431", "-2038.1231", "6277.7471", "10814.983", "0.0731", "50"},
				        {"RFM segment playbook", "3", "1763", "-9331.9912", "-4226.0294", "10599.7508", "-0.0492", "1617"},
				        {"Uplift ranking (greedy)", "4", "5000", "38914.2587", "64158.3829", "9229.7825", "0.7472", "85"},
				        {"Optimized (MIP)", "5", "5000", "42648.7522", "64773.8093", "12904.7417", "0.7543", "94"},
				        {"Optimized, risk-averse (MIP on LCB)", "6", "4239", "40336.3685", "57727.196", "10230.8813", "0.6723", "60"},
				        {"Oracle optimum (true effects)", "7", "5000", "29062.0542", "85868.0939", "9999.9975", "1.0", "0"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"policy", type text}, {"policy_order", Int64.Type}, {"contacts", Int64.Type}, {"predicted_value", type number}, {"true_value", type number}, {"true_spend", type number}, {"share_of_oracle", type number}, {"customers_losing_money", Int64.Type}})
				in
				    Typed
