table price_scenarios
	lineageTag: 6f282625-fe9d-5163-bc8c-aa7fd551c7b3

	column zone_id
		dataType: string
		lineageTag: 48f2fbb3-8bb8-53a3-bd5d-20a8631e8e79
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		lineageTag: 2cccb8c5-5e03-51a3-bb2e-5bed18ad57d8
		summarizeBy: none
		sourceColumn: period

	column price_change
		dataType: double
		formatString: 0.0%
		lineageTag: c0c035fb-329a-5c6f-8047-ede4ea46ce89
		summarizeBy: none
		sourceColumn: price_change

	column demand_index
		dataType: double
		formatString: 0.0%
		lineageTag: 364f9e8a-f633-5344-9b18-15106c24c5af
		summarizeBy: none
		sourceColumn: demand_index

	column revenue_index
		dataType: double
		formatString: 0.0%
		lineageTag: 31d0991a-30a0-59c6-9fa0-0c2d3ceaf511
		summarizeBy: none
		sourceColumn: revenue_index

	partition price_scenarios = m
		mode: import
		source =
				let
				    Source = #table(type table [#"zone_id" = nullable text, #"period" = nullable text, #"price_change" = nullable text, #"demand_index" = nullable text, #"revenue_index" = nullable text], {
				        {"0", "Off-peak", "-0.3", "120.8916", "84.6241"},
				        {"0", "Off-peak", "-0.2", "112.6027", "90.0821"},
				        {"0", "Off-peak", "-0.1", "105.7644", "95.188"},
				        {"0", "Off-peak", "0.0", "100.0", "100.0"},
				        {"0", "Off-peak", "0.05", "97.4381", "102.31"},
				        {"0", "Off-peak", "0.1", "95.0566", "104.5623"},
				        {"0", "Peak", "-0.3", "122.1872", "85.531"},
				        {"0", "Peak", "-0.2", "113.3561", "90.6849"},
				        {"0", "Peak", "-0.1", "106.098", "95.4882"},
				        {"0", "Peak", "0.0", "100.0", "100.0"},
				        {"0", "Peak", "0.05", "97.2961", "102.161"},
				        {"0", "Peak", "0.1", "94.7862", "104.2648"},
				        {"0", "Weekend", "-0.3", "141.4516", "99.0161"},
				        {"0", "Weekend", "-0.2", "124.2292", "99.3833"},
				        {"0", "Weekend", "-0.1", "110.7871", "99.7084"},
				        {"0", "Weekend", "0.0", "100.0", "100.0"},
				        {"0", "Weekend", "0.05", "95.367", "100.1353"},
				        {"0", "Weekend", "0.1", "91.1496", "100.2646"},
				        {"1", "Off-peak", "-0.3", "128.9677", "90.2774"},
				        {"1", "Off-peak", "-0.2", "117.2517", "93.8014"},
				        {"1", "Off-peak", "-0.1", "107.8042", "97.0238"},
				        {"1", "Off-peak", "0.0", "100.0", "100.0"},
				        {"1", "Off-peak", "0.05", "96.58", "101.409"},
				        {"1", "Off-peak", "0.1", "93.4281", "102.7709"},
				        {"1", "Peak", "-0.3", "127.9917", "89.5942"},
				        {"1", "Peak", "-0.2", "116.6958", "93.3566"},
				        {"1", "Peak", "-0.1", "107.5625", "96.8063"},
				        {"1", "Peak", "0.0", "100.0", "100.0"},
				        {"1", "Peak", "0.05", "96.6804", "101.5144"},
				        {"1", "Peak", "0.1", "93.6179", "102.9797"},
				        {"1", "Weekend", "-0.3", "145.9768", "102.1837"},
				        {"1", "Weekend", "-0.2", "126.7008", "101.3607"},
				        {"1", "Weekend", "-0.1", "111.8224", "100.6402"},
				        {"1", "Weekend", "0.0", "100.0", "100.0"},
				        {"1", "Weekend", "0.05", "94.9571", "99.7049"},
				        {"1", "Weekend", "0.1", "90.3858", "99.4244"},
				        {"2", "Off-peak", "-0.3", "133.2046", "93.2432"},
				        {"2", "Off-peak", "-0.2", "119.647", "95.7176"},
				        {"2", "Off-peak", "-0.1", "108.8385", "97.9546"},
				        {"2", "Off-peak", "0.0", "100.0", "100.0"},
				        {"2", "Off-peak", "0.05", "96.1539", "100.9616"},
				        {"2", "Off-peak", "0.1", "92.6246", "101.887"},
				        {"2", "Peak", "-0.3", "133.4489", "93.4142"},
				        {"2", "Peak", "-0.2", "119.7843", "95.8274"},
				        {"2", "Peak", "-0.1", "108.8974", "98.0077"},
				        {"2", "Peak", "0.0", "100.0", "100.0"},
				        {"2", "Peak", "0.05", "96.1298", "100.9363"},
				        {"2", "Peak", "0.1", "92.5792", "101.8371"},
				        {"2", "Weekend", "-0.3", "152.0313", "106.4219"},
				        {"2", "Weekend", "-0.2", "129.9635", "103.9708"},
				        {"2", "Weekend", "-0.1", "113.1729", "101.8556"},
				        {"2", "Weekend", "0.0", "100.0", "100.0"},
				        {"2", "Weekend", "0.05", "94.4307", "99.1522"},
				        {"2", "Weekend", "0.1", "89.4096", "98.3505"},
				        {"3", "Off-peak", "-0.3", "139.5084", "97.6559"},
				        {"3", "Off-peak", "-0.2", "123.1587", "98.527"},
				        {"3", "Off-peak", "-0.1", "110.3353", "99.3018"},
				        {"3", "Off-peak", "0.0", "100.0", "100.0"},
				        {"3", "Off-peak", "0.05", "95.5476", "100.325"},
				        {"3", "Off-peak", "0.1", "91.4871", "100.6359"},
				        {"3", "Peak", "-0.3", "138.3023", "96.8116"},
				        {"3", "Peak", "-0.2", "122.4915", "97.9932"},
				        {"3", "Peak", "-0.1", "110.0526", "99.0474"},
				        {"3", "Peak", "0.0", "100.0", "100.0"},
				        {"3", "Peak", "0.05", "95.6612", "100.4442"},
				        {"3", "Peak", "0.1", "91.6997", "100.8696"},
				        {"3", "Weekend", "-0.3", "159.5616", "111.6932"},
				        {"3", "Weekend", "-0.2", "133.9542", "107.1634"},
				        {"3", "Weekend", "-0.1", "114.8007", "103.3206"},
				        {"3", "Weekend", "0.0", "100.0", "100.0"},
				        {"3", "Weekend", "0.05", "93.8083", "98.4987"},
				        {"3", "Weekend", "0.1", "88.262", "97.0882"},
				        {"4", "Off-peak", "-0.3", "144.2668", "100.9868"},
				        {"4", "Off-peak", "-0.2", "125.7703", "100.6162"},
				        {"4", "Off-peak", "-0.1", "111.4339", "100.2905"},
				        {"4", "Off-peak", "0.0", "100.0", "100.0"},
				        {"4", "Off-peak", "0.05", "95.1103", "99.8658"},
				        {"4", "Off-peak", "0.1", "90.6709", "99.7379"},
				        {"4", "Peak", "-0.3", "144.8148", "101.3703"},
				        {"4", "Peak", "-0.2", "126.0689", "100.8551"},
				        {"4", "Peak", "-0.1", "111.5587", "100.4029"},
				        {"4", "Peak", "0.0", "100.0", "100.0"},
				        {"4", "Peak", "0.05", "95.0609", "99.814"},
				        {"4", "Peak", "0.1", "90.5791", "99.637"},
				        {"4", "Weekend", "-0.3", "164.1495", "114.9047"},
				        {"4", "Weekend", "-0.2", "136.3511", "109.0809"},
				        {"4", "Weekend", "-0.1", "115.766", "104.1894"},
				        {"4", "Weekend", "0.0", "100.0", "100.0"},
				        {"4", "Weekend", "0.05", "93.4452", "98.1175"},
				        {"4", "Weekend", "0.1", "87.5959", "96.3555"},
				        {"5", "Off-peak", "-0.3", "149.366", "104.5562"},
				        {"5", "Off-peak", "-0.2", "128.5333", "102.8266"},
				        {"5", "Off-peak", "-0.1", "112.5831", "101.3248"},
				        {"5", "Off-peak", "0.0", "100.0", "100.0"},
				        {"5", "Off-peak", "0.05", "94.6594", "99.3924"},
				        {"5", "Off-peak", "0.1", "89.8332", "98.8165"},
				        {"5", "Peak", "-0.3", "149.8681", "104.9077"},
				        {"5", "Peak", "-0.2", "128.8035", "103.0428"},
				        {"5", "Peak", "-0.1", "112.6948", "101.4253"},
				        {"5", "Peak", "0.0", "100.0", "100.0"},
				        {"5", "Peak", "0.05", "94.616", "99.3468"},
				        {"5", "Peak", "0.1", "89.7526", "98.7279"},
				        {"5", "Weekend", "-0.3", "168.2952", "117.8066"},
				        {"5", "Weekend", "-0.2", "138.4954", "110.7963"},
				        {"5", "Weekend", "-0.1", "116.6221", "104.9599"},
				        {"5", "Weekend", "0.0", "100.0", "100.0"},
				        {"5", "Weekend", "0.05", "93.1269", "97.7833"},
				        {"5", "Weekend", "0.1", "87.0141", "95.7155"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"zone_id", type text}, {"period", type text}, {"price_change", type number}, {"demand_index", type number}, {"revenue_index", type number}})
				in
				    Typed
