table price_plan
	lineageTag: 5ef27ee0-5130-5cea-8d3c-168487405d55

	column zone_id
		dataType: string
		lineageTag: 4a95663c-2bf0-5fc8-9621-7ae72bb72427
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		lineageTag: f602d351-60e3-57ef-bab1-83e5ae0dab78
		summarizeBy: none
		sourceColumn: period

	column price_change
		dataType: double
		formatString: 0.0%
		lineageTag: 0ffb19ea-e09d-5825-b2fc-11533c42f010
		summarizeBy: none
		sourceColumn: price_change

	column forecast_trips
		dataType: double
		formatString: #,0.00
		lineageTag: bc673aa8-95de-52e7-8bf1-39d0c1cb58cc
		summarizeBy: sum
		sourceColumn: forecast_trips

	column campaign_trips
		dataType: double
		formatString: #,0.00
		lineageTag: ae78632d-5a50-55f1-a045-ab62b8d79282
		summarizeBy: sum
		sourceColumn: campaign_trips

	column contribution_change
		dataType: double
		formatString: #,0.00
		lineageTag: c1b81634-f1ff-5726-b7af-8fbf47b9d54f
		summarizeBy: sum
		sourceColumn: contribution_change

	partition price_plan = m
		mode: import
		source =
				let
				    Source = #table(type table [#"zone_id" = nullable text, #"period" = nullable text, #"price_change" = nullable text, #"forecast_trips" = nullable text, #"campaign_trips" = nullable text, #"contribution_change" = nullable text], {
				        {"0", "Off-peak", "0.1", "7763.6062", "471.2585", "2220.1662"},
				        {"0", "Peak", "0.1", "8444.0344", "360.0765", "1816.1662"},
				        {"0", "Weekend", "0.1", "4350.5437", "401.7557", "75.3041"},
				        {"1", "Off-peak", "0.1", "7287.2782", "485.5088", "1124.941"},
				        {"1", "Peak", "0.1", "6479.7914", "381.1", "1251.6813"},
				        {"1", "Weekend", "-0.3", "6711.1566", "366.418", "522.0448"},
				        {"2", "Off-peak", "0.1", "7402.0266", "472.6212", "734.7629"},
				        {"2", "Peak", "0.1", "6706.4914", "385.0934", "891.0316"},
				        {"2", "Weekend", "-0.3", "7000.5227", "397.0496", "1443.4502"},
				        {"3", "Off-peak", "0.1", "7349.9307", "435.214", "259.4453"},
				        {"3", "Peak", "0.1", "6646.84", "260.8974", "437.8563"},
				        {"3", "Weekend", "-0.3", "7562.2517", "213.2932", "2804.7674"},
				        {"4", "Off-peak", "-0.3", "11098.943", "416.4762", "440.4684"},
				        {"4", "Peak", "-0.1", "7631.9029", "146.2697", "181.2105"},
				        {"4", "Weekend", "-0.3", "7476.134", "124.6324", "3942.3399"},
				        {"5", "Off-peak", "-0.3", "11622.3945", "634.0716", "2533.004"},
				        {"5", "Peak", "-0.2", "10816.1031", "379.9242", "1407.4633"},
				        {"5", "Weekend", "-0.2", "6162.8036", "375.9369", "3436.1497"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"zone_id", type text}, {"period", type text}, {"price_change", type number}, {"forecast_trips", type number}, {"campaign_trips", type number}, {"contribution_change", type number}})
				in
				    Typed
