table sequential_looks
	lineageTag: 2452e6cb-eed0-5abf-9c2a-898148f04bbc

	column arm
		dataType: string
		lineageTag: a7295647-0607-58d2-83de-27dcdcc9ad90
		summarizeBy: none
		sourceColumn: arm

	column day
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 54619bcb-71b1-5d3b-8823-6c6190354b1c
		summarizeBy: none
		sourceColumn: day

	column z
		dataType: double
		formatString: 0.0%
		lineageTag: cff9fa8d-c4ba-501b-a78c-c7af5cf427ab
		summarizeBy: none
		sourceColumn: z

	column boundary
		dataType: double
		formatString: 0.0%
		lineageTag: 7739e7fc-d509-592f-8086-54b3f4d65e1f
		summarizeBy: none
		sourceColumn: boundary

	partition sequential_looks = m
		mode: import
		source =
				let
				    Source = #table(type table [#"arm" = nullable text, #"day" = nullable text, #"z" = nullable text, #"boundary" = nullable text], {
				        {"Off-peak 15% off", "10", "5.6316", "4.7745"},
				        {"Off-peak 15% off", "20", "6.8707", "3.3761"},
				        {"Off-peak 15% off", "30", "7.2358", "2.7566"},
				        {"10% off every trip", "10", "8.8174", "4.7745"},
				        {"10% off every trip", "20", "9.913", "3.3761"},
				        {"10% off every trip", "30", "10.7274", "2.7566"},
				        {"Weekend 20% off", "10", "6.1821", "4.7745"},
				        {"Weekend 20% off", "20", "7.2824", "3.3761"},
				        {"Weekend 20% off", "30", "8.3355", "2.7566"},
				        {"Spend & get $10", "10", "7.3972", "4.7745"},
				        {"Spend & get $10", "20", "8.5246", "3.3761"},
				        {"Spend & get $10", "30", "9.6683", "2.7566"},
				        {"Fifth trip free", "10", "10.0977", "4.7745"},
				        {"Fifth trip free", "20", "12.6443", "3.3761"},
				        {"Fifth trip free", "30", "14.258", "2.7566"},
				        {"Off-peak pass ($30 cap)", "10", "3.0046", "4.7745"},
				        {"Off-peak pass ($30 cap)", "20", "3.4792", "3.3761"},
				        {"Off-peak pass ($30 cap)", "30", "4.0218", "2.7566"},
				        {"500 bonus points", "10", "5.8508", "4.7745"},
				        {"500 bonus points", "20", "5.7487", "3.3761"},
				        {"500 bonus points", "30", "6.0176", "2.7566"},
				        {"1,500 bonus points", "10", "6.9903", "4.7745"},
				        {"1,500 bonus points", "20", "7.8031", "3.3761"},
				        {"1,500 bonus points", "30", "8.1165", "2.7566"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"arm", type text}, {"day", type date}, {"z", type number}, {"boundary", type number}})
				in
				    Typed
