table zone_capacity
	lineageTag: 35ebcb3e-10f3-54df-8730-460113309bc4

	column zone_id
		dataType: string
		lineageTag: e507adb6-ddea-5e2e-832e-12ceca1c8fc8
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		lineageTag: 4c79415f-8aa8-55a0-a9ee-0f31e733376d
		summarizeBy: none
		sourceColumn: period

	column baseline_forecast
		dataType: double
		formatString: #,0.00
		lineageTag: 309ab207-91a6-5b2c-bc11-760a8f5f7155
		summarizeBy: sum
		sourceColumn: baseline_forecast

	column campaign_trips
		dataType: double
		formatString: #,0.00
		lineageTag: 1e48192e-34e6-5396-8c9c-6653a80542eb
		summarizeBy: sum
		sourceColumn: campaign_trips

	column reserve_trips
		dataType: double
		formatString: #,0.00
		lineageTag: dbc01916-ff96-5cea-b656-0397756766a9
		summarizeBy: sum
		sourceColumn: reserve_trips

	column capacity_trips
		dataType: double
		formatString: #,0.00
		lineageTag: b795f561-d8d3-541a-9b6d-30ca51ddaca6
		summarizeBy: sum
		sourceColumn: capacity_trips

	column free_after_campaign
		dataType: double
		formatString: #,0.00
		lineageTag: 55826d58-e91f-5586-a598-0040245d5eff
		summarizeBy: sum
		sourceColumn: free_after_campaign

	partition zone_capacity = m
		mode: import
		source =
				let
				    Source = #table(type table [#"zone_id" = nullable text, #"period" = nullable text, #"baseline_forecast" = nullable text, #"campaign_trips" = nullable text, #"reserve_trips" = nullable text, #"capacity_trips" = nullable text, #"free_after_campaign" = nullable text], {
				        {"0", "Off-peak", "8167.3515", "419.2207", "1633.4703", "17160.0", "6939.9574"},
				        {"0", "Peak", "8908.5054", "306.8613", "1781.7011", "14608.0", "3610.9322"},
				        {"0", "Weekend", "4772.9708", "348.0587", "954.5942", "9104.0", "3028.3762"},
				        {"1", "Off-peak", "7799.8798", "435.0816", "1559.976", "16478.0", "6683.0626"},
				        {"1", "Peak", "6921.5277", "330.9938", "1384.3055", "8756.0", "119.173"},
				        {"1", "Weekend", "4597.4138", "325.9318", "919.4828", "8960.0", "3117.1716"},
				        {"2", "Off-peak", "7991.4291", "415.6833", "1598.2858", "16456.0", "6450.6017"},
				        {"2", "Peak", "7244.0571", "328.9572", "1448.8114", "9372.0", "350.1743"},
				        {"2", "Weekend", "4604.6574", "355.5428", "920.9315", "8944.0", "3062.8683"},
				        {"3", "Off-peak", "8033.84", "480.3145", "1606.768", "16478.0", "6357.0775"},
				        {"3", "Peak", "7248.488", "315.15", "1449.6976", "9438.0", "424.6644"},
				        {"3", "Weekend", "4739.3919", "332.4285", "947.8784", "9288.0", "3268.3013"},
				        {"4", "Off-peak", "7693.343", "559.9975", "1538.6686", "16588.0", "6795.9909"},
				        {"4", "Peak", "6841.153", "295.8912", "1368.2306", "9900.0", "1394.7252"},
				        {"4", "Weekend", "4554.4659", "320.7335", "910.8932", "9096.0", "3309.9075"},
				        {"5", "Off-peak", "7781.1511", "586.185", "1556.2302", "16214.0", "6290.4337"},
				        {"5", "Peak", "8397.3697", "324.5945", "1679.4739", "13728.0", "3326.5619"},
				        {"5", "Weekend", "4449.826", "329.6795", "889.9652", "8872.0", "3202.5293"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"zone_id", type text}, {"period", type text}, {"baseline_forecast", type number}, {"campaign_trips", type number}, {"reserve_trips", type number}, {"capacity_trips", type number}, {"free_after_campaign", type number}})
				in
				    Typed
