"""Write docs/model_cards/*.md from the latest run's metrics. Run after the pipeline."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "model_cards"


def load(name):
    return json.loads((ROOT / "outputs" / name).read_text())


def table(rows, headers):
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def card(name, title, sections):
    body = [
        f"# {title}",
        "",
        "_Generated by `scripts/build_model_cards.py` from the latest pipeline run._",
        "",
    ]
    for heading, text in sections:
        body += [f"## {heading}", "", text.strip(), ""]
    (OUT / f"{name}.md").write_text("\n".join(body), encoding="utf-8", newline="\n")


def classifier(name, title, purpose, population, metrics):
    m = metrics["customer"][name]
    test = m["test_calibrated"]
    board = [
        (algo, f"{v['roc_auc']:.3f}", f"{v['brier']:.4f}", f"{v['ece_10bins']:.3f}")
        for algo, v in m["validation_uncalibrated"].items()
    ]
    card(
        name,
        title,
        [
            ("Purpose", purpose),
            ("Target and population", population),
            (
                "Selection",
                "Logistic regression, histogram gradient boosting and XGBoost are fitted on monthly snapshots from "
                "July 2024 to January 2025. The champion has the lowest validation Brier score (April 2025), then a "
                "Platt calibrator is fitted on that fold. Validation leaderboard (uncalibrated):\n\n"
                + table(board, ["Algorithm", "AUC", "Brier", "ECE"])
                + f"\n\nChampion: **{m['champion']}**.",
            ),
            (
                "Held-out result (July 2025, untouched)",
                table(
                    [
                        (
                            f"{test['roc_auc']:.3f}",
                            f"{test['pr_auc']:.3f}",
                            f"{test['brier']:.4f}",
                            f"{test['ece_10bins']:.3f}",
                            f"{test['lift_at_10']:.2f}",
                            f"{test['n']:,}",
                            f"{test['prevalence']:.1%}",
                        )
                    ],
                    ["AUC", "PR-AUC", "Brier", "ECE", "Lift@10%", "n", "Prevalence"],
                ),
            ),
            (
                "Use and limits",
                "A descriptive score for segmentation and reporting. It is not used to target offers: the policy "
                "evaluation shows that travel propensity correlates negatively with the value an offer creates. "
                "Synthetic population; no protected characteristics are used or available.",
            ),
            (
                "Monitoring and retraining",
                "Prediction PSI against the July test scores and feature PSI each batch; review above 0.2. Retrain "
                "only after matured labels confirm a drop in AUC or calibration, and only through the same "
                "validation-then-test promotion.",
            ),
        ],
    )


def main():
    metrics = load("model_metrics.json")
    uplift = load("uplift_metrics.json")
    elasticity = load("elasticity_metrics.json")
    policy = load("policy_value.json")
    OUT.mkdir(parents=True, exist_ok=True)
    for path in OUT.glob("*.md"):
        path.unlink()
    classifier(
        "propensity",
        "Travel propensity",
        "Probability that a customer travels at least once in the next 30 days.",
        "All customers with an account before the snapshot date. Features end the day before each snapshot.",
        metrics,
    )
    classifier(
        "churn",
        "90-day inactivity (churn)",
        "Probability of no trips in the next 90 days.",
        "Historically active customers (at least 3 trips in the prior 90 days).",
        metrics,
    )
    classifier(
        "attrition",
        "Declining use (attrition)",
        "Probability that trips in the next 90 days fall below half of the prior 90 days - an early warning "
        "before full inactivity.",
        "Historically active customers.",
        metrics,
    )

    clv = metrics["customer"]["clv"]
    card(
        "clv",
        "Customer value",
        [
            ("Purpose", "Projected 12-month contribution for prioritisation and reporting."),
            (
                "Method",
                clv["method"] + " A BG/NBD + Gamma-Gamma model is fitted as an independent benchmark.",
            ),
            (
                "Held-out result",
                f"90-day contribution MAE {clv['test']['mae']:.2f} against {clv['test']['baseline_mae']:.2f} for the "
                f"historical-margin baseline. Serving: **{clv['champion']}** (the simpler model wins ties).",
            ),
            (
                "Limits",
                "The 12-month projection is a heuristic, not a validated CLV. It does not enter the optimizer's "
                "objective, which uses incremental value only.",
            ),
        ],
    )

    seg = metrics["customer"]["segmentation"]
    card(
        "segmentation",
        "Segmentation",
        [
            ("Purpose", "Describe behavioural groups for reporting and analyst work."),
            (
                "Method",
                "Rule-based RFM segments; K-Means (5 clusters) and a Gaussian mixture whose size is chosen by BIC on "
                "log-scaled frequency, spend, distance, period mix, digital activity and recency.",
            ),
            (
                "Evidence",
                f"K-Means silhouette {seg['kmeans']['silhouette']:.3f}, Davies-Bouldin "
                f"{seg['kmeans']['davies_bouldin']:.2f}, bootstrap ARI "
                f"{min(seg['kmeans']['bootstrap_adjusted_rand']):.2f}-{max(seg['kmeans']['bootstrap_adjusted_rand']):.2f}. "
                f"Gaussian mixture: {seg['gmm']['clusters']} components, silhouette {seg['gmm']['silhouette']:.3f}. "
                f"K-Means vs mixture ARI {seg['agreement']['kmeans_vs_gmm_ari']:.2f}; K-Means vs RFM "
                f"{seg['agreement']['kmeans_vs_rfm_ari']:.2f}.",
            ),
            (
                "Limits",
                "Segments are descriptive; the plan targets by estimated incremental value, not segment.",
            ),
        ],
    )

    anomaly = metrics["customer"]["anomaly"]
    forest = anomaly["evaluation_against_planted"].get("isolation_forest", {})
    robust = anomaly["evaluation_against_planted"].get("robust_z_score", {})
    card(
        "anomaly",
        "Account anomaly review",
        [
            (
                "Purpose",
                "Queue unusual accounts (cloned transponders, night travel far from home) for review.",
            ),
            ("Method", anomaly["method"]),
            (
                "Evidence against planted anomalies",
                table(
                    [
                        (
                            "Isolation Forest",
                            forest.get("caught"),
                            forest.get("planted"),
                            f"{forest.get('precision', 0):.0%}",
                            f"{forest.get('recall', 0):.0%}",
                            f"{forest.get('pr_auc', 0):.3f}",
                        ),
                        (
                            "Robust z-score",
                            robust.get("caught"),
                            robust.get("planted"),
                            f"{robust.get('precision', 0):.0%}",
                            f"{robust.get('recall', 0):.0%}",
                            f"{robust.get('pr_auc', 0):.3f}",
                        ),
                    ],
                    ["Detector", "Caught", "Planted", "Precision", "Recall", "PR-AUC"],
                ),
            ),
            ("Limits", "A review signal with a fixed capacity, not fraud adjudication."),
        ],
    )

    rows = []
    for offer, values in uplift.items():
        if not isinstance(values, dict) or "selected" not in values:
            continue
        production = values.get("ensemble", values[values["selected"]])
        rows.append(
            (
                offer,
                f"{production['oracle']['value_spearman']:.2f}",
                f"{production['qini']:.2f}",
                f"{values['blp']['slope']:.2f} ± {1.96 * values['blp']['slope_se']:.2f}",
            )
        )
    pooled = [
        (
            r["learner"],
            f"{r['pooled_loss']:.2f}",
            f"{r['gap_to_best']:.2f}",
            f"{r['se']:.2f}",
            "yes" if r["member"] else "no",
        )
        for r in uplift.get("ensemble_selection", [])
    ]
    members = ", ".join(uplift.get("ensemble_members", []))
    persistence = uplift["persistence"]
    check = uplift.get("blp_calibration_check", {})
    predicted, true = policy["production_predicted_value"], policy["production_true_value"]
    if predicted > true:
        curse = (
            f"The optimized plan was predicted to create ${predicted:,.0f} and in simulation truly creates "
            f"${true:,.0f}. Selection favours customers whose value is overestimated; treat plan-level predictions "
            "as optimistic and validate them with a holdout."
        )
    else:
        curse = (
            f"The optimized plan was predicted to create ${predicted:,.0f} and in simulation truly creates "
            f"${true:,.0f}: here the estimates are conservative in level (the learners under-state value by "
            f"${-check.get('mean_value_bias_raw', 0):.2f} per customer-offer on average), which outweighs the "
            "winner's curse that selecting on noisy estimates always adds. The plan depends on the ranking, not the "
            "level; the level is validated by the randomised policy trial, not assumed."
        )
    card(
        "uplift",
        "Incremental response (causal targeting)",
        [
            (
                "Purpose",
                "Estimate, for every customer and offer, the incremental trips by travel period an offer causes; "
                "the offer's terms turn them into expected value and cost for the optimizer.",
            ),
            (
                "Data",
                f"The July 2025 {len(rows) + 1}-arm customer-randomised trial (blocked on 90-day trips and trend). "
                "Learners fit on the training fold, are chosen on the validation fold and are scored on untouched "
                "test customers.",
            ),
            (
                "Selection",
                "S-, T-, X- and DR-learners are fitted for every offer. Their per-customer doubly robust validation "
                "losses are pooled across offers, and production averages every learner within one paired standard "
                f"error of the best. Selected: **{members}**.\n\n"
                + table(pooled, ["Learner", "Pooled loss", "Gap to best", "Paired SE", "In ensemble"]),
            ),
            (
                "Evidence by offer",
                "Rank correlation of the production estimates with the simulator's true value (simulation-only "
                "check), held-out value Qini on observed outcomes, and the BLP heterogeneity slope (1 = calibrated "
                "spread):\n\n"
                + table(rows, ["Offer", "ρ vs truth", "Qini", "BLP slope (95%)"])
                + f"\n\nMean rank correlation: {uplift['selected_value_spearman']:.2f}.",
            ),
            (
                "Carry-over",
                f"Days 31-90 margin per dollar of in-window gross contribution, regression-adjusted: discounts "
                f"{persistence['discount']['point_estimate']:.2f} (90% CI {persistence['discount']['ci_low']:.2f}-"
                f"{persistence['discount']['ci_high']:.2f}), loyalty {persistence['loyalty']['point_estimate']:.2f} "
                f"(90% CI {persistence['loyalty']['ci_low']:.2f}-{persistence['loyalty']['ci_high']:.2f}). Planning uses "
                "the 20th percentile.",
            ),
            (
                "Calibration (diagnostic, not applied)",
                f"A BLP recalibration would move the mean value bias from ${check.get('mean_value_bias_raw', 0):.2f} "
                f"to ${check.get('mean_value_bias_calibrated', 0):.2f} per customer-offer and increase bias for "
                f"{check.get('offers_where_calibration_increased_bias', '?')} of {len(rows)} offers in this run. It is "
                "not applied: when it was first tested it increased bias for 7 of 8 offers, and a 15% validation fold "
                "is too small to estimate the level reliably.",
            ),
            ("Prediction against truth", curse),
        ],
    )

    recovery = elasticity["elasticity_rmse_vs_truth"]
    card(
        "elasticity",
        "Price elasticity",
        [
            (
                "Purpose",
                "Demand response to the effective price, by zone, travel period and customer segment.",
            ),
            (
                "Method",
                "Log-log OLS per cell with weather and calendar controls on randomised daily price tests, shrunk "
                "toward the period x segment mean by empirical Bayes.",
            ),
            (
                "Evidence (simulation check)",
                table(
                    [
                        ("Empirical Bayes (serving)", f"{recovery['elasticity']:.3f}"),
                        ("Cell OLS", f"{recovery['ols_elasticity']:.3f}"),
                        ("Pooled by period x segment", f"{recovery['pooled_elasticity']:.3f}"),
                        ("Monotone gradient boosting", f"{recovery['boosting_elasticity']:.3f}"),
                    ],
                    ["Method", "RMSE vs true elasticity"],
                )
                + f"\n\n95% intervals contain the true elasticity in {recovery['ci_coverage']:.0%} of cells. Gradient "
                f"boosting predicts demand comparably (MAE {elasticity['boosting_test_mae']:.2f} vs "
                f"{elasticity['cell_ols_test_mae']:.2f}) yet recovers the price response worst.",
            ),
            (
                "Limits",
                "Constant elasticity within the tested -30% to +10% range; illustrative effective prices.",
            ),
        ],
    )

    demand = metrics["demand"]
    test = demand["test"]
    card(
        "demand",
        "30-day demand forecast",
        [
            (
                "Purpose",
                "Baseline trips by zone, travel period and day for the October window; feeds capacity.",
            ),
            (
                "Method",
                "Weekly fixed origins, each forecasting the next 30 days from origin-time information only. The "
                "learned model predicts a multiplicative correction to the same-weekday mean; it competes with the "
                "same-weekday mean and a seasonal naive on validation, must beat the same-weekday baseline on test, "
                "and is refit on all history before forecasting October.",
            ),
            (
                "Held-out result",
                f"Serving: **{demand['champion']}**. MAE {test['mae']:.1f} trips per cell-day against "
                f"{test['same_weekday_mean_mae']:.1f} (same-weekday mean) and {test['seasonal_naive_mae']:.1f} "
                f"(seasonal naive), over {test['test_origins']} held-out origins. Split-conformal 90% intervals "
                f"covered {test['interval_coverage_90']:.0%}.",
            ),
            (
                "Limits",
                "Weather enters only through history, not a weather forecast. Hour and direction are disaggregated "
                "with historical shares, not modelled.",
            ),
        ],
    )
    print(f"wrote {len(list(OUT.glob('*.md')))} model cards")


if __name__ == "__main__":
    main()
