table customer_360
	lineageTag: 6daf37c3-88b8-4385-8b89-b38e280bdd78

	column customer_id
		dataType: string
		lineageTag: 46302710-7cd8-431d-ab1d-84c838e3f0ef
		summarizeBy: none
		sourceColumn: customer_id

	column as_of
		dataType: string
		lineageTag: 2e8b6f9d-aecf-49e6-8e60-686a76741861
		summarizeBy: none
		sourceColumn: as_of

	column tenure_days
		dataType: int64
		lineageTag: 125f039a-85a5-451d-80a0-5d228204068e
		summarizeBy: none
		sourceColumn: tenure_days

	column business_flag
		dataType: int64
		lineageTag: 9da5b0bc-3fc1-4913-810f-e3bd05603fa3
		summarizeBy: none
		sourceColumn: business_flag

	column autopay
		dataType: int64
		lineageTag: 9111c455-b2f0-4a05-963e-8484e37240a1
		summarizeBy: none
		sourceColumn: autopay

	column transponder_flag
		dataType: int64
		lineageTag: f579054a-71b1-4ef1-b0b9-b57e53fc8069
		summarizeBy: none
		sourceColumn: transponder_flag

	column home_zone
		dataType: int64
		lineageTag: 0bc37176-74e2-4e56-a929-b5dfc5895b82
		summarizeBy: none
		sourceColumn: home_zone

	column eligible
		dataType: boolean
		lineageTag: ed7771af-12b7-4c6f-8943-dd38423f087d
		summarizeBy: none
		sourceColumn: eligible

	column account_status
		dataType: string
		lineageTag: 5ab6b227-2c84-41f3-bfc5-8e481cf28271
		summarizeBy: none
		sourceColumn: account_status

	column trips_7d
		dataType: int64
		lineageTag: d8763edf-99ef-4290-bd42-06b6b07fad0a
		summarizeBy: none
		sourceColumn: trips_7d

	column trips_30d
		dataType: int64
		lineageTag: cbd2d90f-c20d-42e2-81f9-18d51031684c
		summarizeBy: none
		sourceColumn: trips_30d

	column trips_90d
		dataType: int64
		lineageTag: e959ed3d-189f-4972-b523-d483d3007480
		summarizeBy: none
		sourceColumn: trips_90d

	column trips_previous90d
		dataType: int64
		lineageTag: ecca51de-2e7e-4408-894d-1dc56d6944a2
		summarizeBy: none
		sourceColumn: trips_previous90d

	column spend_30d
		dataType: double
		lineageTag: ef723880-da82-473b-b4ac-bd9de1316c19
		summarizeBy: none
		sourceColumn: spend_30d

	column spend_90d
		dataType: double
		lineageTag: e355e38a-8324-42a3-bd44-3550533f75b8
		summarizeBy: none
		sourceColumn: spend_90d

	column spend_365d
		dataType: double
		lineageTag: e65ba1a4-194c-435c-a1dd-d9bd19f6f5e3
		summarizeBy: none
		sourceColumn: spend_365d

	column avg_toll
		dataType: double
		lineageTag: 4304e8fe-97d0-48f8-8d00-5de68e4c1a76
		summarizeBy: none
		sourceColumn: avg_toll

	column avg_distance_km
		dataType: double
		lineageTag: fb3d2989-41b2-43d6-bf34-f80c708ebf4d
		summarizeBy: none
		sourceColumn: avg_distance_km

	column peak_share
		dataType: double
		lineageTag: 58013169-c135-444f-95d6-e70c3faa87fd
		summarizeBy: none
		sourceColumn: peak_share

	column weekend_share
		dataType: double
		lineageTag: f5c44b98-db20-4403-9ad3-93d2db7b3264
		summarizeBy: none
		sourceColumn: weekend_share

	column discount_90d
		dataType: double
		lineageTag: df83d337-9c6a-4b6a-94f1-725dacf8bff9
		summarizeBy: none
		sourceColumn: discount_90d

	column recency_days
		dataType: int64
		lineageTag: c1fee305-1d23-4c75-820e-9d20485cefde
		summarizeBy: none
		sourceColumn: recency_days

	column digital_events_30d
		dataType: int64
		lineageTag: 57e5d830-f4d5-4d9f-bb7e-90512dbd189b
		summarizeBy: none
		sourceColumn: digital_events_30d

	column app_logins_30d
		dataType: int64
		lineageTag: 39dfefcc-edb2-4ceb-9aae-93c6037447e6
		summarizeBy: none
		sourceColumn: app_logins_30d

	column offer_views_30d
		dataType: int64
		lineageTag: b2f8c2f4-9a19-441b-9c65-a92240e73b53
		summarizeBy: none
		sourceColumn: offer_views_30d

	column email_opens_30d
		dataType: int64
		lineageTag: c3c81005-9985-4b84-95fb-e14763654ae0
		summarizeBy: none
		sourceColumn: email_opens_30d

	column points_earned_to_date
		dataType: double
		lineageTag: 4c7e51d1-431f-4b64-ba2f-20a56ff2004c
		summarizeBy: none
		sourceColumn: points_earned_to_date

	column feature_max_timestamp
		dataType: string
		lineageTag: 60835db0-18e8-42d2-92c9-b5b8eba69d1f
		summarizeBy: none
		sourceColumn: feature_max_timestamp

	column frequency_trend
		dataType: double
		lineageTag: 6230b764-f14a-41de-85ee-fc09de1a3625
		summarizeBy: none
		sourceColumn: frequency_trend

	column digital_engagement_score
		dataType: double
		lineageTag: 5185718e-90d0-408f-bc17-79df1ea87608
		summarizeBy: none
		sourceColumn: digital_engagement_score

	column propensity_probability
		dataType: double
		lineageTag: 09641e7a-326f-43a0-89b7-03448f70d7c8
		summarizeBy: none
		sourceColumn: propensity_probability

	column churn_probability
		dataType: double
		lineageTag: 3404e301-c108-4a7d-99b6-272e230bd178
		summarizeBy: none
		sourceColumn: churn_probability

	column attrition_probability
		dataType: double
		lineageTag: d8eaa621-b754-4f71-bb5b-5c96d5ed6547
		summarizeBy: none
		sourceColumn: attrition_probability

	column expected_margin_90d
		dataType: double
		lineageTag: 9a7385ee-192e-40fd-bd6c-4ecd4712cd32
		summarizeBy: none
		sourceColumn: expected_margin_90d

	column clv_12m
		dataType: double
		lineageTag: fa2c3423-89a8-466c-8edd-cf153400ca91
		summarizeBy: none
		sourceColumn: clv_12m

	column cluster
		dataType: int64
		lineageTag: 054b3c1a-bd17-4971-a13d-296353951785
		summarizeBy: none
		sourceColumn: cluster

	column rfm_segment
		dataType: string
		lineageTag: 0777b924-3326-4008-873c-1dc802c45c9f
		summarizeBy: none
		sourceColumn: rfm_segment

	column anomaly_score
		dataType: double
		lineageTag: a0e89e3e-65e2-4bb0-b5f4-aaf2c25cf3ca
		summarizeBy: none
		sourceColumn: anomaly_score

	column anomaly_flag
		dataType: boolean
		lineageTag: 3a56e17a-e8dd-48f2-a683-de0d59466b8f
		summarizeBy: none
		sourceColumn: anomaly_flag

	column probabilistic_clv_12m
		dataType: double
		lineageTag: 8a435993-1c3b-4622-be64-bcfa872a37c7
		summarizeBy: none
		sourceColumn: probabilistic_clv_12m

	column probability_alive
		dataType: double
		lineageTag: c8bebd71-dd39-4db6-9947-af031bf34d79
		summarizeBy: none
		sourceColumn: probability_alive

	partition customer_360 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/customer_360.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"customer_id", type text}, {"as_of", type text}, {"tenure_days", Int64.Type}, {"business_flag", Int64.Type}, {"autopay", Int64.Type}, {"transponder_flag", Int64.Type}, {"home_zone", Int64.Type}, {"eligible", type logical}, {"account_status", type text}, {"trips_7d", Int64.Type}, {"trips_30d", Int64.Type}, {"trips_90d", Int64.Type}, {"trips_previous90d", Int64.Type}, {"spend_30d", type number}, {"spend_90d", type number}, {"spend_365d", type number}, {"avg_toll", type number}, {"avg_distance_km", type number}, {"peak_share", type number}, {"weekend_share", type number}, {"discount_90d", type number}, {"recency_days", Int64.Type}, {"digital_events_30d", Int64.Type}, {"app_logins_30d", Int64.Type}, {"offer_views_30d", Int64.Type}, {"email_opens_30d", Int64.Type}, {"points_earned_to_date", type number}, {"feature_max_timestamp", type text}, {"frequency_trend", type number}, {"digital_engagement_score", type number}, {"propensity_probability", type number}, {"churn_probability", type number}, {"attrition_probability", type number}, {"expected_margin_90d", type number}, {"clv_12m", type number}, {"cluster", Int64.Type}, {"rfm_segment", type text}, {"anomaly_score", type number}, {"anomaly_flag", type logical}, {"probabilistic_clv_12m", type number}, {"probability_alive", type number}}, "en-CA")
				in
				    Typed
