table decision_table
	lineageTag: d0242a34-6039-45a8-b7fe-1dfb4b8be125

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Selected contacts' = DISTINCTCOUNT(decision_table[customer_id])
		formatString: #,0
		lineageTag: 5ec0da81-3ede-4957-b168-f2a589a12209

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Expected additional trips' = SUM(decision_table[incremental_trips])
		formatString: #,0.0
		lineageTag: 543aa7e8-c1ae-4721-b583-ae67c69dda48

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Expected incentive costs' = SUM(decision_table[cost])
		formatString: $#,0.00
		lineageTag: a87867a8-1077-4228-bf44-818c3829a988

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Expected net contribution' = SUM(decision_table[net_contribution])
		formatString: $#,0.00
		lineageTag: c447520c-67b3-4e7d-95b7-2eb051627487

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Net ROI' = DIVIDE([Expected net contribution], [Expected incentive costs])
		formatString: 0.0%
		lineageTag: 439bba5c-c88e-42d5-9b3f-f41e97d6ff26

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Points awarded' = SUM(decision_table[points])
		formatString: #,0
		lineageTag: 1f60fbf0-bf39-4d41-9083-84d7e7f24d3a

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure Customers = COUNTROWS(customer_360)
		formatString: #,0
		lineageTag: f57ae2b7-5dce-48a5-b91e-4ba5bc3d41d7

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Average projected value' = AVERAGE(customer_360[clv_12m])
		formatString: $#,0.00
		lineageTag: 0176639a-29c3-4d57-b25a-4fa418253a5d

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure Trips = SUM(monthly_performance[trips])
		formatString: #,0
		lineageTag: 6e973235-cf93-439d-b5d9-0900dfbbed17

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure Revenue = SUM(monthly_performance[revenue])
		formatString: $#,0
		lineageTag: 30059ab7-868c-4552-8215-dd2cb2675f6b

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure Utilization = DIVIDE(SUM(zone_capacity[baseline_forecast])+SUM(zone_capacity[allocated_trips]),SUM(zone_capacity[capacity_trips]))
		formatString: 0.0%
		lineageTag: bebf8d00-2d67-4dd9-96b7-2da7008a3863

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Remaining headroom' = SUM(zone_capacity[remaining_with_reserve])
		formatString: #,0.0
		lineageTag: 422da22c-8f33-417a-bc4d-6baa8544e398

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Mean price demand index' = AVERAGE(pricing_scenarios[demand_index])
		formatString: 0.0
		lineageTag: c0d9e689-5119-4c1f-b103-5a209a9ab610

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Mean response lift' = AVERAGE(experiment_results[difference])
		formatString: 0.0%
		lineageTag: e9f33f57-13c4-4dee-b7fb-3f5f66466c82

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Test AUC' = AVERAGE(model_metrics[roc_auc])
		formatString: 0.000
		lineageTag: a97ba857-bfd1-4ef1-82ee-e912b5d7ea2e

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Mean price revenue index' = AVERAGE(pricing_scenarios[revenue_index])
		formatString: 0.0
		lineageTag: 65889656-1a8f-46f8-8e88-f148e44a2a89

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Loyalty additional trips' = CALCULATE([Expected additional trips], decision_table[offer_id] = "loyalty_500")
		formatString: #,0.0
		lineageTag: d5a9f56e-d409-4dba-83a0-ad4c92e8dfdf

	/// Synthetic portfolio result. Forecasts do not represent measured business impact.
	measure 'Mean test Brier' = AVERAGE(model_metrics[brier])
		formatString: 0.000
		lineageTag: b1ec941f-39ae-4edf-a997-78b18d5915df

	column customer_id
		dataType: string
		lineageTag: eb367287-bc25-40e3-b14a-5566b1a4dafe
		summarizeBy: none
		sourceColumn: customer_id

	column offer_id
		dataType: string
		lineageTag: d3d40aee-767b-4004-b578-f50fe566d829
		summarizeBy: none
		sourceColumn: offer_id

	column incremental_response
		dataType: double
		lineageTag: 2e95dd34-8733-42db-8bf7-65d81f36b14f
		summarizeBy: none
		sourceColumn: incremental_response

	column predicted_treated_trips
		dataType: double
		lineageTag: 4fd99b91-9c11-4d19-846c-472cf0354e18
		summarizeBy: none
		sourceColumn: predicted_treated_trips

	column predicted_baseline_trips
		dataType: double
		lineageTag: 38bcd780-ca36-402a-8f00-bc3ef006fe7e
		summarizeBy: none
		sourceColumn: predicted_baseline_trips

	column incremental_trips_raw
		dataType: double
		lineageTag: fcc4eb38-9230-45fb-9759-5e40cb416e77
		summarizeBy: none
		sourceColumn: incremental_trips_raw

	column enrollment_probability
		dataType: double
		lineageTag: af8a0fc9-77e5-46af-a06d-39a848b5cd36
		summarizeBy: none
		sourceColumn: enrollment_probability

	column redemption_probability
		dataType: double
		lineageTag: b65f44a3-fe0f-4277-9e34-6634665bf772
		summarizeBy: none
		sourceColumn: redemption_probability

	column eligible
		dataType: boolean
		lineageTag: 5132044b-9131-4e3b-83e1-d3724e042e6e
		summarizeBy: none
		sourceColumn: eligible

	column home_zone
		dataType: int64
		lineageTag: befb185d-9d5f-4af9-9e01-3e7b97f85067
		summarizeBy: none
		sourceColumn: home_zone

	column avg_toll
		dataType: double
		lineageTag: c676434d-ea6d-4794-b2de-418e7aacdbf2
		summarizeBy: none
		sourceColumn: avg_toll

	column clv_12m
		dataType: double
		lineageTag: f06cdf33-056b-4654-9060-52caf9f1b7e8
		summarizeBy: none
		sourceColumn: clv_12m

	column rfm_segment
		dataType: string
		lineageTag: 375f6465-5940-4315-84fa-cc5e3d332b9b
		summarizeBy: none
		sourceColumn: rfm_segment

	column propensity_probability
		dataType: double
		lineageTag: 2a4394ea-5334-4b50-ba3a-d783db8ad5ec
		summarizeBy: none
		sourceColumn: propensity_probability

	column trips_90d
		dataType: int64
		lineageTag: d26a131e-2917-47dc-988f-5d5845d09886
		summarizeBy: none
		sourceColumn: trips_90d

	column offer_name
		dataType: string
		lineageTag: c68deb4a-1a0f-4a2c-a6b7-10da169bec28
		summarizeBy: none
		sourceColumn: offer_name

	column period
		dataType: string
		lineageTag: 7f52f633-d1db-4f67-8073-a55460e77d31
		summarizeBy: none
		sourceColumn: period

	column discount_pct
		dataType: double
		lineageTag: f14876c5-033f-4c20-a6a6-ab0d621f1fd5
		summarizeBy: none
		sourceColumn: discount_pct

	column inventory
		dataType: int64
		lineageTag: b95c582c-4483-4194-ae21-059479e22452
		summarizeBy: none
		sourceColumn: inventory

	column incremental_trips
		dataType: double
		lineageTag: c3e5fb53-75c6-4451-bb6d-db7b4b7f94eb
		summarizeBy: none
		sourceColumn: incremental_trips

	column cost
		dataType: double
		lineageTag: 8eab00d0-3d22-48e5-b273-48b687a1dd89
		summarizeBy: none
		sourceColumn: cost

	column points
		dataType: int64
		lineageTag: 2d0358e5-2e9c-4107-b15f-1df27747921b
		summarizeBy: none
		sourceColumn: points

	column zone_id
		dataType: int64
		lineageTag: fc06ca2f-2cb5-4040-a583-2f3937a84ceb
		summarizeBy: none
		sourceColumn: zone_id

	column incremental_gross_contribution
		dataType: double
		lineageTag: 6eebdc4e-ddc0-476f-bea1-822a7c39b813
		summarizeBy: none
		sourceColumn: incremental_gross_contribution

	column net_contribution
		dataType: double
		lineageTag: 70e23d56-0a22-4188-bf06-b0e4e4454725
		summarizeBy: none
		sourceColumn: net_contribution

	column network_value
		dataType: double
		lineageTag: 04f1963c-f928-4475-ab4e-d7da26a9064b
		summarizeBy: none
		sourceColumn: network_value

	column objective_value
		dataType: double
		lineageTag: af328c4d-9d76-43cf-931e-dd5fd2e4528b
		summarizeBy: none
		sourceColumn: objective_value

	column candidate_id
		dataType: int64
		lineageTag: 8f440665-34fb-4cc2-a7b5-e8a06858826e
		summarizeBy: none
		sourceColumn: candidate_id

	partition decision_table = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/decision_table.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"customer_id", type text}, {"offer_id", type text}, {"incremental_response", type number}, {"predicted_treated_trips", type number}, {"predicted_baseline_trips", type number}, {"incremental_trips_raw", type number}, {"enrollment_probability", type number}, {"redemption_probability", type number}, {"eligible", type logical}, {"home_zone", Int64.Type}, {"avg_toll", type number}, {"clv_12m", type number}, {"rfm_segment", type text}, {"propensity_probability", type number}, {"trips_90d", Int64.Type}, {"offer_name", type text}, {"period", type text}, {"discount_pct", type number}, {"inventory", Int64.Type}, {"incremental_trips", type number}, {"cost", type number}, {"points", Int64.Type}, {"zone_id", Int64.Type}, {"incremental_gross_contribution", type number}, {"net_contribution", type number}, {"network_value", type number}, {"objective_value", type number}, {"candidate_id", Int64.Type}}, "en-CA")
				in
				    Typed
