table dim_offer
	lineageTag: 44b81192-f9bd-44e1-800d-b65078f728e9

	column offer_id
		dataType: string
		lineageTag: 2b4a48d1-5a40-4b70-bcbe-8a5ca0a923bc
		summarizeBy: none
		sourceColumn: offer_id

	column offer_name
		dataType: string
		lineageTag: 9186f4c4-9440-4af4-a4db-d16561d5a138
		summarizeBy: none
		sourceColumn: offer_name

	column period
		dataType: string
		lineageTag: 5895620f-511e-456f-ba37-e0a4cf37e0a8
		summarizeBy: none
		sourceColumn: period

	column discount_pct
		dataType: double
		lineageTag: 95452b57-fb37-4966-859c-253178c85ff9
		summarizeBy: none
		sourceColumn: discount_pct

	column inventory
		dataType: int64
		lineageTag: cf2dc405-7aa5-42f2-bf69-34f9ba0cbab0
		summarizeBy: none
		sourceColumn: inventory

	partition dim_offer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/dim_offer.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"offer_id", type text}, {"offer_name", type text}, {"period", type text}, {"discount_pct", type number}, {"inventory", Int64.Type}}, "en-CA")
				in
				    Typed
