table monthly_performance
	lineageTag: d7b20bc4-941a-491b-b4e0-18ad80fea08d

	column month
		dataType: string
		lineageTag: 792381e6-632b-4fbe-84ea-1e39a4326fb8
		summarizeBy: none
		sourceColumn: month

	column trips
		dataType: int64
		lineageTag: 47f2fc70-bfe9-4264-97ad-ff2d643d1898
		summarizeBy: none
		sourceColumn: trips

	column revenue
		dataType: double
		lineageTag: 5c5788e5-bfa9-4fa2-ac76-5c869d7b48bc
		summarizeBy: none
		sourceColumn: revenue

	column savings
		dataType: double
		lineageTag: d32ef364-bd56-4ff5-8484-250ac482e25b
		summarizeBy: none
		sourceColumn: savings

	partition monthly_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/monthly_performance.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"month", type text}, {"trips", Int64.Type}, {"revenue", type number}, {"savings", type number}}, "en-CA")
				in
				    Typed
