table zone_capacity
	lineageTag: 7c65726e-458f-4746-bc8d-2ff6cafab636

	column zone_id
		dataType: int64
		lineageTag: 97cc44b9-ea33-43ce-9807-40d19aa772e0
		summarizeBy: none
		sourceColumn: zone_id

	column period
		dataType: string
		lineageTag: fe3cb635-3fac-4b66-a5e3-268ad0a02473
		summarizeBy: none
		sourceColumn: period

	column baseline_forecast
		dataType: double
		lineageTag: 980aaf55-0e8b-42fd-8182-3c01143dac3f
		summarizeBy: none
		sourceColumn: baseline_forecast

	column daily_capacity
		dataType: double
		lineageTag: 712886a4-ef29-4468-975d-c2fe411c2e4b
		summarizeBy: none
		sourceColumn: daily_capacity

	column capacity_trips
		dataType: double
		lineageTag: 9fd7f858-62f0-4037-a96e-2129f2d6adc5
		summarizeBy: none
		sourceColumn: capacity_trips

	column reserve_trips
		dataType: double
		lineageTag: 30442148-70bc-4cad-b858-d7c9b275d4cd
		summarizeBy: none
		sourceColumn: reserve_trips

	column available_trips
		dataType: double
		lineageTag: b8bfe301-cd30-43fd-9d83-24ed5e46de6d
		summarizeBy: none
		sourceColumn: available_trips

	column baseline_over_capacity
		dataType: boolean
		lineageTag: 3a033c30-6739-4575-994c-5f3c7f22bd0a
		summarizeBy: none
		sourceColumn: baseline_over_capacity

	column allocated_trips
		dataType: double
		lineageTag: cf044b15-1087-4c60-833d-0d1eb1e2e35a
		summarizeBy: none
		sourceColumn: allocated_trips

	column final_utilization
		dataType: double
		lineageTag: 5228a1aa-758e-4803-866d-d930ab6d4d16
		summarizeBy: none
		sourceColumn: final_utilization

	column remaining_with_reserve
		dataType: double
		lineageTag: 86655aea-1254-4948-a3bf-813fc2477502
		summarizeBy: none
		sourceColumn: remaining_with_reserve

	partition zone_capacity = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/kush2/decision-intelligence-platform/outputs/powerbi/zone_capacity.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"zone_id", Int64.Type}, {"period", type text}, {"baseline_forecast", type number}, {"daily_capacity", type number}, {"capacity_trips", type number}, {"reserve_trips", type number}, {"available_trips", type number}, {"baseline_over_capacity", type logical}, {"allocated_trips", type number}, {"final_utilization", type number}, {"remaining_with_reserve", type number}}, "en-CA")
				in
				    Typed
